### ISSUE TITLE
Iron chunks should have a dissolve effect

### ISSUE THREAD

**Issue by icedjuro** [Revolutionary-Games/Thrive#1166]
Buckly noticed that when approaching an iron chunk, large or small, it just disappeared,

**Comment by hhyyrylainen** [comment]
I've noticed that chunks behind the player disappear, which is likely the spawn system despawning them.
However things in front of the player shouldn't disappear like that.
I think that this might be caused by the chunks running out of iron and disappearing because of that.
Changing the iron chunks to not dissolve should fix this, but then there are iron chunks floating around that don't give any iron.

**Comment by hhyyrylainen** [comment]
Another fix, which I think we should have anyway, is that when chunks dissolve they would be given some kind of graphical effect.
