### ISSUE TITLE
AI improvements

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1175]
AI needs improvements:
- [ ] teach it to stop moving when it’s low on ATP
- [ ] get it to more actively seek out energy sources (maybe this means better chunk handling and predation?)
- [ ] get small cells to run away more effectively
- [ ] should know how to use a pilus effectively
- [ ] make run and tumble only count useful compounds

**Comment by hhyyrylainen** [comment]
This is now no longer impeded.

**Comment by hhyyrylainen** [comment]
If the existing AI is keeping someone from working on it, a full rewrite is also acceptable for the AI as long as it ends up better than the current AI (and knows about those things listed in this issue).

**Comment by FuJa0815** [comment]
One thing that would be really fitting the game would be some kind of generational neural network.
The neural network has its inner state and the environment as its inputs and has the actions it can perform as its outputs.
In the beginning, the neural network outputs useless data, but using natural selection the smarter brains should survive and should multiply.
This should lead to neural networks getting smarter overtime, the ai reacting to environment changes and maybe even altering its behavior due to the player.

This would be a completely new AI and would need much time to implement, but would fit the game really well

**Comment by hhyyrylainen** [comment]
If someone picks this up, there's already some changes done in this PR: https://github.com/Revolutionary-Games/Thrive/pull/1776
