### ISSUE TITLE
Fix floating toxins not damaging the player

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1193]
I ran into some of the floating toxins (X's), my cell blinked red, but I did not take any HP damage.

**Comment by crodnu** [comment]
Is this meant to be on the game? Toxin projectiles don't even use the X model anymore and i don't think they add much to the game anyway so i'd say we should probably remove them (or at the very least have them in some toxic biome, not just randomly in the ice biome). If you do want to keep them tho, the problem is that there's no actual code that handles them, so we should add a new field to the json or something to do that.

**Comment by crodnu** [comment]
Actually nvm im blind lol
i still mantain my point that they should be removed tho

**Comment by hhyyrylainen** [comment]
We can discuss later with game designers if they don't provide any value anymore.
