### ISSUE TITLE
Player global population is incorrectly applied to all patches

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1236]
I noticed that when the player reproduces in another patch, all of the patches the player species is in, get set to the global total population, this is not intended. Instead the patches should preserve their individual populations.

**Comment by matthewpaul-us** [comment]
I don't think this is isolated to the player species. Was taking a look at the populations across patches and I think it's all species that exist in the patch. Taking a look at the report, it seems to have the correct numbers, so I think this may just be a GUI bug on the patch map.
![image](https://user-images.githubusercontent.com/1484070/82217116-fa27c880-98e7-11ea-9a8e-c5699d6e1798.png)
Here are two patches. Notice the populations are the same across both. They also match the sum of a species across all patches.
![image](https://user-images.githubusercontent.com/1484070/82217320-43781800-98e8-11ea-9fca-fe04474c4b13.png)
![image](https://user-images.githubusercontent.com/1484070/82217328-45da7200-98e8-11ea-816f-d88d5b7280ec.png)

**Comment by Kasterisk** [comment]
Can confirm, the code for the species list is incorrectly using the global species population to get the population value:
https://github.com/Revolutionary-Games/Thrive/blob/9d404b21976a36e32b1a37cfd08e24e613f6d3bd/src/microbe_stage/editor/MicrobeEditorGUI.cs#L1306
So, the fix is simply just to replace the `species.Population` to `patch.GetSpeciesPopulation(species)` to get the population of a species in a single patch.
