### ISSUE TITLE
Models for organelles.

### ISSUE THREAD

**Issue by jjonj** [Revolutionary-Games/Thrive#125]
We need some models for basic organelles:
Nucleus, Normal Vacuole, Agent Vacuole (possibly multiple), Cilia and mitochondria
Also an animated Flagelium (Note that animations require special treatment to be exported successfully, see #102). 
Animations can possibly also be added to the other models later. 

It would be nice if an Agent Vacuole could be rushed out quick for the next release (We will have it spawn in the enviroment to be unlockable)!

STATUS 03/03/2015:
 - Nucleus: Needs 90 degree rotation (tried doing this myself, but when I exported it wasn't rotated anyway)
 - Cilia: Waiting to see if Poisonchocolate returns
 - mitochondria: Cheese might have one lying around, unknown
 - Agent: We have one done, could use more
 - Vacuole: Not yet made I believe
 - Chloroplast: One at the bottom of this issue: https://github.com/Revolutionary-Games/Thrive/issues/143 (untested)

To make sure things will work with the game, look through this tutorial: http://thrivegame.canadaboard.net/t1402-basic-blender-modeling-animation-and-exporting-to-ogre-tutorial?highlight=animation

**Comment by Alex-the-666** [comment]
once again I am gong to ask if you guys need any models. do you?

**Comment by jjonj** [comment]
It's hard to keep track of :b but I imagine we could always use some extra models for various agent vacuoles (we have the "oxytoxy" one already)!

**Comment by tjblazer85** [comment]
Hey Guys! I've made three Vacuole Models! Just vote on which one you guys think should be used in the game. After looking at the other models in the game, I've decided to take a look into how to make my models look better and I figured out how to use the texture option in blender! Hopefully my models are up to par now.

Here are Vacuoles 1,2, and 3:
![vacuole 1](https://cloud.githubusercontent.com/assets/4619968/6841435/862306a8-d3c5-11e4-9e0d-028c5bd30b09.png)
![vacuole 2](https://cloud.githubusercontent.com/assets/4619968/6841436/892e0f0a-d3c5-11e4-8413-f9bf8ad796d9.png)
![vacuole 3](https://cloud.githubusercontent.com/assets/4619968/6841437/8fa63e48-d3c5-11e4-8505-b355da82e6b3.png)

Download link is here: https://dl.dropboxusercontent.com/u/137682043/Vacuoles.rar

P.S. @jjonj, I've checked on the Chloroplast model in blender, I think it should work with Ogre but I don't have the right programs to make sure. Can you tell me what programs I need to test the models in Ogre? I might need it for future models.

**Comment by tjblazer85** [comment]
@jjonj, I wanted to ask what another agent vacuole should look like? Should I keep it close to the way the one we already have looks like or should I make it more varied? Also, why do we need another agent vacuole, and how many more do we need?

**Comment by TritiumH** [comment]
@tjblazer85 I've exported your model from Blender and opened it with Nimet sadly i don't think this texture displacement is exporting or even the transparency, ogre material settings in blender provide very little options i'm afraid for better looks we'll need shaders, i think a velvet shader would look nice on our models but i'm just getting into all of this.

**Comment by tjblazer85** [comment]
I'll look into it, maybe I can figure something out.

**Comment by jjonj** [comment]
> what another agent vacuole should look like

From a realistic perspective I have no idea, and from an artistic one you are more qualified than I ;)

**Comment by TheCreator--** [comment]
@tjblazer85, all you need to do is use a frenel shader. That way it will be fairly transparent when you look at it directly, but colorful on the sides.

If you guys want, I can send you a .blend file that I did for thrive a while ago.

Here is the link of it in action:
http://youtu.be/_kBdRXBu1MY

**Comment by jjonj** [comment]
I just made a branch where chloroplast is unlockable, but until we have a working chloroplast model it is just using the toxin model.

**Comment by ChizuNordenstam** [comment]
Didn't the one tjblazer85 posted work?

**Comment by jjonj** [comment]
From above replies it sounds like tritium tested it and it had issues

**Comment by Poisonchocolate** [comment]
Immensely sorry for this, but I had lost track of this project. Anyways, here you go with the cilia model (I didn't add any color as I was unsure of what that should be). Absolutely tell me if anything needs to be changed. Again, I apologize for just disappearing!
![cilia2](https://cloud.githubusercontent.com/assets/10107731/8255500/58f93788-166e-11e5-9de6-30ee50f9e45b.png)
The rendering is very low quality because this is just to show the work.

**Comment by jjonj** [comment]
Looks quite good! Is it animated? Regarding color I think you have some artistic freedom there!

**Comment by Poisonchocolate** [comment]
In it's current state I am able to animate it, but I'm not entirely sure how to go about animating it using an armature in the way explained on the post about how to export models from blender to OGRE. I think I might have an idea on how to do so, though.

Regarding texturing, would I be able to use shaders, or would I actually have to make textures in image form for models?

**Comment by jjonj** [comment]
You can find some info on ogre materials here: http://www.ogre3d.org/tikiwiki/Materials

**Comment by Poisonchocolate** [comment]
I honestly cannot figure out how to set materials with blender2ogre. I can export the mesh with animations itself, but I really have no clue with setting materials. So blender textures will not carry over?

**Comment by Oliveriver** [comment]
With the membrane coming relatively soon, it might be a good idea to work on implementing the organelle models, seeing as hexagons floating around inside the membrane might not look particularly good.

Sorry about the somewhat instructional post coming. If you think something here needs changing, please say - all this is written assuming the current concept is correct.

Before that though, we need to decide on how big each organelle should be. External organelles all attach to the outside of the membrane and move with it. All of them use one edge of one hex in the editor, so the width of their attachment point should stay about that size. Their length is up to the creator (in future, length will be upgradeable, but for now this isn't an issue). Most external organelles are also animated in some way.

Internal organelles have differing sizes. Each is defined by a small hex arrangement, and the model should fit within it. Something like this (except the models should actually look like proper organelles, not just weird blobs):

![organelle hexes](https://cloud.githubusercontent.com/assets/7430433/8831730/35f1d482-309c-11e5-931b-208689498e5f.png)

The nucleus, endoplasmic reticulum and golgi apparatus are special cases  - though they count as separate organelles, the player can't move them, and their organelle models should overlap and be attached to each other.

Vacuoles should come in multiple shapes and sizes, all made from arrangements of hexagons but retaining the same sort of appearance. It might even be possible for vacuoles to expand as they store more compounds, but this isn't necessary and is up to the modelers. All internal organelles should float around inside the cell once in-game.

Here's a full list of organelles, both internal and external. All the sizes for external organelles need to be decided on:

High priority:
- (Internal) Nucleus/Endoplasmic Reticulum/Golgi Apparatus
- (Internal) Mitochondrion
- (Internal) Vacuoles of various sizes
- (Internal) Chloroplast
- (External) Flagellum
- (External) Agent Secretor*

Low priority:
- (Internal) Thermoplast
- (Internal) Slime Gland**
- (Internal) Bioluminescent Organelle
- (External) Cilia
- (External) Predatory Pilus
- (External) Engulfing Edge
- (External) Lamellipodia

* The agent secretor is in the game as an internal organelle, but eventually should be external. Come to think of it, the game doesn't currently handle external organelles at all (even flagella are placed like internal organelles), so this might be needed first.

** Slime glands are basically just exploding vacuoles holding slime. Models are needed for all the same shapes of slime gland as vacuoles.

For more detailed information on organelles and visuals, see:
http://thrivegame.wikidot.com/gdd-microbe:gameplay#toc21
http://thrivegame.wikidot.com/gdd-microbe:visuals#toc2

**Comment by Poisonchocolate** [comment]
I have a few questions.

1. Do organelles have physjxs? i.e. collisions and deformation. If so, then a hex wouldn't work very well for collision or at all for deformation.

2. A bit of clarification on exterior organelles? You say they take up one hex edge. But the membrane isn't based on hexes, correct? This wouldn't work for the deformation the membrane would have, because the organelles won't be flexible.

I feel like its more likely that I'm missing something rather than you having made a mistake,so please correct any assumptions.

**Comment by Oliveriver** [comment]
> Do organelles have physjxs? i.e. collisions and deformation. If so, then a hex wouldn't work very well for collision or at all for deformation.

Very unlikely. They probably would collide, but there wouldn't be any deformation involved, they'd just bounce off one another.

> A bit of clarification on exterior organelles? You say they take up one hex edge. But the membrane isn't based on hexes, correct? This wouldn't work for the deformation the membrane would have, because the organelles won't be flexible.

The membrane is based on hex arrangement - it's drawn using an algorithm around the cytoplasm and organelles placed using hexes in the editor. Something like this:

![membrane rendering](https://cloud.githubusercontent.com/assets/7430433/8848562/288c2c04-3130-11e5-8c29-6b7ecfc66528.png)

You can see a flagellum attached to the edge of one hexagon, and rendered on the membrane based on its position. Since external organelles can be added to any edge, there can be many of them attached to a single hex:

![membrane rendering 2](https://cloud.githubusercontent.com/assets/7430433/8848598/73a1f188-3130-11e5-8550-b609881b905c.png)

That might cause problems when rendering them in-game (especially if more flagella were added to the edges of the hexes on either side). I guess the only way around that would be to have an algorithm which aligns external organelles so none overlap or anything.

**Comment by Oliveriver** [comment]
Here's an overview of everything I've talked about in a far more understandable picture form:

![organelle hexes complete](https://cloud.githubusercontent.com/assets/7430433/8848977/d70fd674-3133-11e5-9313-03e31638d430.png)

They are, in order from left to right: the cytoplasm structure, organelle placement, rendered membrane and organelles, and an example of environmental distortion and floating organelles.

**Comment by Poisonchocolate** [comment]
Alright. So probably the most difficult thing with this is the cilia. It needs to have a special system of some sort to apply it to the membrane.

**Comment by TheCreator--** [comment]
@Oliveriver, very nice job on the images. Here are my 2 cents:

I always thought that the organelles in the cell would remain stationary, but my current membrane prototype does allow for them to move, so I guess that shouldn't really be a problem to do. For collisions, we could let them flow on top of eachother without any collisions since our cell is actually 3-dimensional and the organelles aren't all located in a plane. Another idea would be to use a simple rectangle bounding box for collisions—the organelles never really have to touch. Whichever method we chose, it should be easy to implement.

Here is a link from the old forum that I found that should help with the silhouettes: http://i82.servimg.com/u/f82/14/12/40/46/cellsp11.png

We definitely need good models for the organelles (like the one we have for the toxin organelle currently); however the external organelles are a bit more complicated. The flagellum needs to be a static, tube-like model that will then be animated in the actual program (or we could try to make it completely procedural). I think it should be easy to place by simply attaching its origin to a point on the cells membrane. As for the cilia, their model can simply be attached to all the faces on the cell membrane, using a fresnel shader, so they are only noticible on the sides but not when directly viewed on from the top.

Also, maybe we should move this discussion to the dev forum?

**Comment by Oliveriver** [comment]
> Also, maybe we should move this discussion to the dev forum?

You read my mind: I'm writing an opening post for it already. I'll reply to all your points there.

**Comment by tjblazer85** [comment]
Hey Guys! I'd like to join the discussion and make some new models but I can't login in to the new forums. Any help?

**Comment by Oliveriver** [comment]
Hi @tjblazer85 ! Officially you're meant to submit an application here: http://revolutionarygamesstudio.com/application/

But since you've helped before I think we could skip that and just invite you anyway. We'd need your email though.

**Comment by tjblazer85** [comment]
Thanks a lot @Oliveriver ! Here's my email address: tjtomenes@yahoo.com

**Comment by Oliveriver** [comment]
Ok, it should have been sent.

**Comment by tjblazer85** [comment]
I tried changing my password but it wouldn't work. Also I'm working on a Mitochondria model.
@Oliveriver

**Comment by TheCreator--** [comment]
We got all of the organelle models in this release, so I'm going to go ahead and close this issue.
