### ISSUE TITLE
Fix membrane generation for really big cells

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1274]
The membrane stops working on really big cells. Especially if they are long and thin.

**Comment by CoreyHendrey** [comment]
Just as a note that might help whoever can fix this, adding to the Constants.MEMBRANE_RESOLUTION will cause the long thing cells to re-appear. However, they will all be very square, rather than long and thin.

**Comment by FuJa0815** [comment]
I was not able to reproduce this:
![grafik](https://user-images.githubusercontent.com/30809803/95663999-3e8c5d00-0b44-11eb-88a8-2f1887fe023d.png)
![grafik](https://user-images.githubusercontent.com/30809803/95664005-451ad480-0b44-11eb-9e22-4088aa977a53.png)
![grafik](https://user-images.githubusercontent.com/30809803/95664013-4c41e280-0b44-11eb-8dae-5b06f897c703.png)

**Comment by FuJa0815** [comment]
Only the collision is strange:
![grafik](https://user-images.githubusercontent.com/30809803/95664063-a478e480-0b44-11eb-9a76-72b5b9352b90.png)

**Comment by hhyyrylainen** [comment]
If you zoom out a lot more in the editor, does it then become possible to break it? I've seen screenshots where the membrane is completely just gone when in-game.

**Comment by Nunez2196** [comment]
Working on this.

**Comment by hhyyrylainen** [comment]
I guess as the pilus depends on the membrane coordinates to attach its physics shape, it would also break in this situation.

Also we've been regularly getting reports about this, so this can definitely happen as long as the radius of a cell is too large.

**Comment by Nunez2196** [comment]
so long as these issues are not the result of floating point issues, I think a change of algorithms will fix that.

my real question is, how high priority is this? 

I will probably be done with current visuals this weekend since it's a pretty straight forward shader, membrane generation is probably somewhere like 85 - 90% done, and all the hard stuff is totally functional like Del-Iso, arranging spheres and connections to form a microbe object's geometry skeleton, and I got at least one kernel for Convolution Surfaces totally working (Power Inverse). I guess since I don't have classes for this Winter, if you want me to hyper-focus on that and maybe make a Branch, we could get it done hopefully by next release.

**Comment by hhyyrylainen** [comment]
This isn't the most high priority thing, mostly as if you play normally you'll never encounter this issue. But probably this could be fixed by just making the starting membrane square size bigger (it's set to 10 currently if I remember right). Of course that can have performance consequences.
