### ISSUE TITLE
Flagella orientation calculation fails at 0,0

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1297]
https://community.revolutionarygamesstudio.com/t/general-0-5-0-feedback/2645/5?u=hhyyrylainen

related issue: https://github.com/Revolutionary-Games/Thrive/issues/1500

**Comment by CoreyHendrey** [comment]
So the reason this happens is all External Organelles are rotated to aim at Hex(0,0).

This means when the player removes the default hex at 0,0 and replaces it with an external Organalle, that organelle will always have a rotation of 0.

It is a design problem that we need input with @hhyyrylainen. We have come up with a couple possible solutions:

1. Remove the ability to add External Organelles at Hex(0, 0).
2. Rotate the external organelles to the closest membrane point instead of 0,0.
3. Find the closes Internal Hex and rotate towards that.
4. Average out the size of the cell body to find a weighted "middle" and aim towards that.
5. Keep the players desired rotation on the External Cells instead of overriding it.

**Comment by hhyyrylainen** [comment]
So I think that the best options are: 2 and 5. The reason that option 5 is not used for all flagellum is because the flagella are always teleported to the membrane edge, and as such the player set rotation might not make sense. Also when dividing the extra added flagella get rotated automatically, otherwise cells having divided flagella could have them pointing towards really silly directions.

Also it's been suggested before that we should offset the cell center anyway, as if you make a big cell the turning center doesn't match the center of mass.

**Comment by hhyyrylainen** [comment]
Also affects the pilus, and with the cell origin repositioning this now has a pretty good chance to impact gameplay.
