### ISSUE TITLE
Editor cell speed calculation is incorrect

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1325]
![shot](https://cdn.discordapp.com/attachments/464846875187478548/715030421913731163/unknown.png)
![shot2](https://cdn.discordapp.com/attachments/464846875187478548/715030480252174416/unknown.png)

Probably happened after: https://github.com/Revolutionary-Games/Thrive/pull/1273 was merged

**Comment by Holomanga** [comment]
I think this is a balance issue, rather than a calculation error - I'll check the actual speeds of these cells in gameplay.

**Comment by Holomanga** [comment]
Yep, it's a balance thing; speed of a single hex of cytoplasm in-game is about ~19.5, speed of a cytoplasm hex + flagellum is ~18.5 (measured by printing out `LinearVelocity.Length()` to the console).

The reason is that membrane force is constant for all cells, but the cell with the flagellum is heavier, such that (membrane force)/(cytoplasm mass) > (membrane force + flagellum force)/(cytoplasm mass + flagellum mass)
