### ISSUE TITLE
Add serializer and deserializer for Random

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1340]
in order to save its state

**Comment by DTanxxx** [comment]
Hi hhyyrylainen,

I am using a MacBook and I usually open Thrive with Visual Studio Community Edition for Mac. For some reason the project no longer opens in Visual Studio due to an error saying:
Load failed: Unknown solution item type: {8F3E2DF0-C35C-4265-82FC-BEA011F4A7ED}

I have tried deleting and recloning Thrive but it didn't work. Am I missing something? Thanks.

**Comment by hhyyrylainen** [comment]
That sounds unrelated to "Add serializer and deserializer for Random". Could you open a new issue about that?

**Comment by DTanxxx** [comment]
Yes, will do.

**Comment by DTanxxx** [comment]
Hi hhyyrylainen,

For clarification, is the `Random` here referring to the `System.Random` used in `Spawners` class?

**Comment by hhyyrylainen** [comment]
Yes it is. Currently serializing it results in: `{}` so the seed and current state is lost. It would be nice to store that so that not all Randoms created from a save start with the same seed (the current time) after loading a game.
