### ISSUE TITLE
Add auto-refresh to SaveList after it is shown

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1409]
should probably add a new property to SaveList to refresh after being hidden and remove the extra code from PauseMenu and NewSaveMenu.RefreshExisting

**Comment by DTanxxx** [comment]
Hi hhyyrylainen,
For this issue, would you like the implementation to have the NewSaveMenu.RefreshExisting method and any calls to it completely removed? Also for the auto-refresh property, I take that you would like the save list to refresh itself after it is hidden (when the save menu is closed)? If so, should I try to refresh the save list in NewSaveMenu.ClosePressed instead, rather than adding and updating an auto-refresh property? Thank you for your time.

**Comment by hhyyrylainen** [comment]
I think that most (if not all) of the existing calls to the list refresh can be removed (if there is like a button to refresh the list that should obviously not be removed).
The list refresh should start once the list *becomes* visible and not when hiding it.
The list class itself should have the property for auto refresh on becoming visible.
Then either using the process callback to detect when the visibility of it changes, or perhaps there is a callback from Godot for a control that becomes hidden or visible, trigger the refresh operation.
