### ISSUE TITLE
Improve the separation of big cells on divide (when reproducing after exiting the editor)

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1435]
to make it less likely that the cells might get stuck.

**Comment by Satharis** [comment]
Maybe not a very elegant solution, but can't you just double the separation radius in Microbe.Divide()? I did that as a little test with the freebuild editor and they seem to generally not get stuck with that. With the normal radius it's quite a bit easier since you're often clipping into them on divide.

**Comment by hhyyrylainen** [comment]
Doesn't that approach stop working once the cells get big enough?
Instead the separation distance should be computed from the cell sizes to work at any size.

**Comment by Satharis** [comment]
Yeah, fair, I tried a bit more with really long + shaped cells and it seems the membrane radius doesn't give a very good approximation of the distance between them. Need a more robust approach.
