### ISSUE TITLE
Sometimes returning from the editor spawns an extra daughter cell

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1497]
When exiting the editor there should be 2 player species cells on screen, sometimes there's a third one, which shouldn't spawn.

**Comment by Satharis** [comment]
So I managed to reproduce this. Seems to be what is happening is when you divide it splits your stored compounds between the two cells. However in the player's case, they pick when they divide and so they can collect enough compounds to have double what is needed to split again.

Once you actually divide, the npc cell that gets spawned has enough compounds to immediately divide, so the first process tick into returning from the editor will cause the npc cell to divide and you'll end up with two of them there.

**Comment by hhyyrylainen** [comment]
Ah, okay, that's interesting. Not sure if we need to fix that. Opinions?
We could make it so that the other cell is only given 99% of the resources it should get so that it doesn't have enough to split immediately.

**Comment by Satharis** [comment]
Without really delving into the design aspect of compounds and dividing I'd say my personal thoughts are that it likely _should_ be changed because from the perspective of the player it will probably seem like a bug, since the behavior is not very obvious. Not only does that lead to pointless bug reports but also leads to a feeling of the game being unpolished.

As for the actual fix I'd say if we want to keep the compound and dividing behavior the same(in the design sense), then maybe capping what the daughter cells gets to be half or so of the required amount to divide might be better. I feel like giving 99% would give a lot of weird corner cases like them moving into a compound cloud right away and dividing, giving a similar "what was that?" reaction from players.

**Comment by hhyyrylainen** [comment]
At least for the player cell they should receive all the compounds they are entitled to as it is a legitimate strategy to store up compound to quickly divide again. For the AI daughter cell multiplying the amounts it gets by 0.9f would be good then? In a very dense cloud it could still divide immediately, but that could happen even if it doesn't get any compounds at all as some clouds have ridiculously high concentration.

**Comment by Satharis** [comment]
Yeah I don't see a real issue with the player getting all compounds if that's intended design. For the daughter cell I'm not sure if it should be multiplied or just capped to that amount? Does the amount they receive need to be reduced if it's not in danger of quickly dividing?

**Comment by hhyyrylainen** [comment]
It would be more consistent to always apply the "take away some compounds" logic then splitting from the player's cell. That way the splitting logic doesn't need to calculate and see if the new cell has enough compounds to split immediately.

**Comment by Satharis** [comment]
So you suggest splitting it 50/50 with the player cell and npc cell like now? Then multiply the compounds(all compounds?) the npc cell gets by 0.9(0.45)? Does that apply for npc cell to npc cell division?

**Comment by hhyyrylainen** [comment]
My suggestion is to keep the 50/50 split, but in addition:
When the player cell is divided, the NPC daughter cell has the compounds it receives multiplied by 0.9f.

**Comment by Satharis** [comment]
Actually after inspecting the code a bit I don't think that will solve it either. If we use the simple example of a single cell with just cytoplasm it takes 2 units of compound to divide. Normally you can hold 4 units with that configuration. You collect compounds, organelles duplicate and your storage capacity goes to 8.

Now you go to the editor and divide. You get 4 units(since it consumes the 2 during gameplay as you collect them) and the daughter cell gets 4(they actually get slightly less, like 3.99, not sure if thats a rounding error or it not capping compounds collected to the upper limit). Using the 0.9f math they'd get a bit less than 3.6 units from the division, and as far as I know they only need 2 to divide again, so they would still instantly divide again.

**Comment by hhyyrylainen** [comment]
That's actually a good point, so the multiplier needs to be less than 0.5 to properly prevent the immediate duplication. Maybe something like 0.40f?

**Comment by Satharis** [comment]
The problem is since storage capacity doubles, if the player collects to max and then divides it will always be 8 being split in two(in the single hex example), so the daughter cell is basically getting 4 units in that scenario and requires 2 to divide. It'd have to be < 0.25f to not instantly divide. That number comes from the code as it is right now, since it takes the full compounds of the first cell and multiplies it by 0.5f in the code right now to reduce it.

```
Compounds.TakeCompound(compound, amount * 0.5f);

var didntFit = copyEntity.Compounds.AddCompound(compound, amount * 0.5f);
```

**Comment by hhyyrylainen** [comment]
So yeah the code needs to first check how much compounds is needed to divide and give less than that.
Because if you have vacuoles you can store much more compounds related to what your division cost is.

**Comment by Satharis** [comment]
Right vacuoles only need 2 to divide but give 8 storage I believe, so that quickly gets complicated. In fact a single vacuole cell should be able to theoretically triple divide on a full storage capacity(after it doubles). So I guess it's back to my idea of capping what they get to be like 90% of what they need to divide?

**Comment by hhyyrylainen** [comment]
The GUI calls a bunch of functions to determine how many compounds a cell needs to divide in order to show the reproduction indicator. So I think it would be relatively simple to call that stuff in the divide method for the new cell to determine how much resources it is safe to give it.

**Comment by hhyyrylainen** [comment]
`Microbe.CalculateTotalCompounds` is the method you need for that.

**Comment by Satharis** [comment]
Despite the fix I agree some kind of animation or even a delay time before NPC cells can divide again may be useful. But considering the difference in possible storage with vacuoles I think you could still end up in a weird situation of splitting and then the other cell sits there and splits 5 or 6 times in a row because it has a massive amount of extra compound. Not sure if that is desirable.
