### ISSUE TITLE
Investigate why there is no iron spawning in the cave

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1541]
It should be one of the biomes with the most iron.

Edit: it seems that the new patch spawn conditions aren't properly being set when moving to another patch.

**Comment by jkent4444** [comment]
Hi @hhyyrylainen 

Im keen to pick this up next.
If you want to assign this one to me.

**Comment by CoreyHendrey** [comment]
I think you've been added to Rev Games now, so you should be able to assign issues to yourself :)

**Comment by hhyyrylainen** [comment]
Yes, there should be a pending invitation for you.

**Comment by jkent4444** [comment]
No matter I do this value for Iron never changes.
I'm going to confirm if the density is overridden by the spawner somewhere.
![image](https://user-images.githubusercontent.com/2314333/90508137-7e654280-e19a-11ea-9dd1-8788788afcdc.png)

**Comment by hhyyrylainen** [comment]
That's the logging for the initial spawn density. I think it got fixed so that density changes will also be logged.

**Comment by jkent4444** [comment]
Just pulled the latest from master doesn't seem to be coming through.
I'll add some debugging around see if I can trace it.

**Comment by hhyyrylainen** [comment]
This is the print that should be triggered when the densities change after the initial creation of spawners:
https://github.com/Revolutionary-Games/Thrive/blob/0e79166eedcc408980e2215b63cba2c37acb926b/src/microbe_stage/PatchManager.cs#L181

**Comment by hhyyrylainen** [comment]
One person reported that interestingly, if you load a save made in a patch, that correctly sets the spawn frequencies there. Which would indicate that there might be a pretty basic mistake that the spawn frequencies don't re-apply for some reason when changing patches.

**Comment by Maxonovien** [comment]
![image](https://user-images.githubusercontent.com/16361817/124563998-e1a6a480-de40-11eb-9269-91182fd2eec4.png)

I actually found iron after moving in the cave, although it took a bit of time. I rushed there with a single-cytoplasm cell.
Here are Godot logs for chunks: 

> Number of chunks in this patch = 3
> Spawn frequency of FLOATING_HAZARD changed from 11 to 115
> Spawn frequency of SMALL_IRON_CHUNK changed from 57 to 11
> Spawn frequency of BIG_IRON_CHUNK changed from 5 to 11

From these logs, there is indeed less iron chunks in total, which is why they are hard to find. However, there are twice more big chunks, which are iron rich, hence a high total amount of iron in the patch. 

Overall, there is indeed more iron in the cave, but many (many) more sparsely distributed, being centered around a few big chunks, and thus hard to find for the player.

This directly comes from the biomes.json file, as densities are defined as such:
> Mesopelagic - small chunks = 5e-4
> Cave - small chunks = 1e-4
>--
> Mesopelagic - big chunks = 5e-5
> Cave - small chunks = 1e-4

**Comment by hhyyrylainen** [comment]
Would you be willing to make a small PR where you multiply by like 8 the iron values in the cave, for playtesting purposes? Though this doesn't explain why the patch map display seems to say the cave *should* have more iron than other patches, might be density vs amount problem, resulting in different numbers that don't really reflect the gameplay reality?

**Comment by Maxonovien** [comment]
It is to me density vs amount indeed: as per biomes.json, amount is 200 for small chunks and 60,000 (!) for big chunks. With this 300fold difference, multiplying the big chunk ratio by 2 massively outweights divising the small chunk ratio by 5!

I'll do the PR because it's worth testing, but I think that it should overall come with something to prevent this small/big chunks differences to weight so heavily (reducing iron amount/chunk ratio? giving a measurement of density variations in the patch map?), and distord gameplay reality.

**Comment by hhyyrylainen** [comment]
I think two things should be done in addition:
- All chunk amounts for small and big should be consistent between patches
- The ratio between small and large chunks should be the same in all patches (so there isn't some patch where there's vastly more large chunks than small chunks as a ratio when compared to other patches)

**Comment by Maxonovien** [comment]
This seems like a good way to prevent such issues. Implementation-wise, it will likely require to rework jsons parameters (because they do allow free variations, and are intended to work this way). Dealing with constant ratio and amounts across patches would use an external parameter (hardcoded/defined in a different json file - or at least a different json structure).

I can take a look at this afterwards, although I'll still do the minor PR change to allow testing in the mean time (and build from it later on I guess).

**Comment by hhyyrylainen** [comment]
There is a mechanism in SimulationParameters to verify the data after loading. If wanted / required a check could be added to check that the small to big chunk ratio is not too far off.

**Comment by Maxonovien** [comment]
Anyways, changing Json seemingly only fixes logs... (furthermore, it only does so on new games - it also changes displayed proportion on patch map, so I think there was still something about amount vs density)

> Number of chunks in this patch = 3
> Spawn frequency of FLOATING_HAZARD changed from 11 to 115
> Spawn frequency of SMALL_IRON_CHUNK changed from 57 to 115
> Spawn frequency of BIG_IRON_CHUNK changed from 5 to 11

Although the spawn frequency of small iron chunks is equal to the one of toxins, I came across ~40 toxins vs no iron chunk on a new game. Although the black background likely does not help (especially as I'm fully zoomed out for a large vision range), I don't think I missed any.

When increasing frequencies so that small and big chunks are respectively 10 times and 2 times more frequent than toxins, I was only able to find one lone small chunk aswell. Saving and reloading did not help either.

Something else is also off there, I guess.

**Comment by hhyyrylainen** [comment]
Regarding saving, it *may* be the case that the chunk densities are included in the save, so only newly started games will pick up the new values.

**Comment by Maxonovien** [comment]
A quick glance at the saving code lets met think that simulation parameters as a whole are saved, so this would explain that indeed. And there's not much we can do about it, then. I'm investigating the rest though.

**Comment by Maxonovien** [comment]
Although I have little idea about why, reducing density of toxines from 1e-3 to 1e-4 (matching the range of other, iron-filled patches) seems to fix the issue: I've encountered about a dozen iron chunk in a few moves from spawn.

Logs look weird though (no spawn frequency for toxines displayed anymore):

> Number of chunks in this patch = 3
> Spawn frequency of SMALL_IRON_CHUNK changed from 57 to 115
> Spawn frequency of BIG_IRON_CHUNK changed from 5 to 11

**Comment by hhyyrylainen** [comment]
Not *all* of the parameters should be saved. The reason why patch conditions are saved is that they can actually change over time, and it would have been much more complicated to only save values that have changed to allow the defaults to change.

> Logs look weird though (no spawn frequency for toxines displayed anymore):

That just logs the *changes* so if the density is the same as in another patch, then it won't be printed.
