### ISSUE TITLE
Colour filters are broken (in 0.5.1.1)

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1611]
When trying to play with the colour filters on in 0.5.1.1, this is all you get:
![Kuvakaappaus - 2020-09-13 21-41-14](https://user-images.githubusercontent.com/3796411/93025832-f09a3d00-f609-11ea-9a08-04a74c9647f5.png)

**Comment by Satharis** [comment]
Issue seems to be related to the chromatic aberration filter as the UI shows properly when it is disabled. There's a bit of an additional issue in that the color filters don't color the pause menu and options menus correctly(options isn't actually enabled as of this comment). The coloring issue seems to be caused by the fact the pause menu is in a canvas layer object, so it's likely being drawn on top of the color filter.
