### ISSUE TITLE
Make things private in MicrobeEditor.cs

### ISSUE THREAD

**Issue by FuJa0815** [Revolutionary-Games/Thrive#1719]
Everything in this class is public, which is a bit unnecessary.

**Comment by hhyyrylainen** [comment]
After review I think the following things in it should be made private (accessing the other properties etc. would be fine from the editor GUI):
- `public void OnEnterEditor()`
- `public void StartMusic()`
- `public void CalculateEnergyBalanceWithOrganellesAndMembraneType`
- `public void CalculateOrganelleEffectivenessInPatch`

Everything else seems to be used from the outside or has constraints otherwise to need to be public.

**Comment by FuJa0815** [comment]
The following methods are also public, but don't need to:
- `public void Redo()`
- `public void Undo()`
- `public void PlaceOrganelle()`
- `public void RotateRight()`
- `public void RotateLeft()`
- `public void RemoveOrganelle()`

**Comment by hhyyrylainen** [comment]
They need to be, at least fundamentally, as those are also triggered from the GUI (in practice godot can swindle private methods through, but in this case I don't really like how a different class / scene would call private stuff anyway).
So in my opinion those should not be made private.

**Comment by Kasterisk** [comment]
Actually after looking through the code again, most (if not all) gui callback is private methods, should they be made public also?

**Comment by hhyyrylainen** [comment]
I've kinda reasoned that if you have a class and a scene that calls private method callbacks, I think that's actually pretty good, as it's clearly marked that you aren't supposed to call the callbacks from other code, but a kinda part of the class (the scene) is allowed to call the private methods.

**Comment by Kasterisk** [comment]
Ah okay, yeah that makes sense
