### ISSUE TITLE
Evolution progress not saving

### ISSUE THREAD

**Issue by FuJa0815** [Revolutionary-Games/Thrive#1762]
**Describe the bug**

When loading the game you loose 2 Phosphate and Ammonia. Seems like the game does not save the progress to your evolution progress

**To Reproduce**
1. Full up one ressource
2. Quicksave
3. Quickload
4. You loose 2 Points of that ressource

Note: This does not happen if both your evolution ressource bars are full.
Note: If you have less than 2 points of resource banked, your evolution progress only fills up by the amount you had.

**Comment by hhyyrylainen** [comment]
Could you describe this in more detail? Are you saying that if one of your organelles already split, then you lose that amount of resource? Or are you saying that the resources that your organelles absorb (and store inside them) before they split, is lost on load? That second thing very much can be a thing I forgot that needs to be saved.

**Comment by hhyyrylainen** [comment]
I'll have a look at this once I get my saving system changes done.

**Comment by FuJa0815** [comment]
The absorbed materials are not saved and therefore drawn from your resources

**Comment by hhyyrylainen** [comment]
So my second guess was right
> Or are you saying that the resources that your organelles absorb (and store inside them) before they split, is lost on load? 

And the amount of absorbed compounds in an organelle do indeed get lost, and should be saved instead.

**Comment by Aquasheep3000** [comment]
Related to this issue, which I also just encountered in 0.5.2.0 rc-1, when loading a save with a full evolution bar of both ammonia and phosphate, the phosphate appeared to be stored according to the storage display on the left rather than applied to the phosphate bar.

Furthermore, when I regained enough ammonia and phosphate to evolve, the bar was full and I could not click it. Screenshots
 and save attached.

Phosphate allocated to storage instead of to evolution bar on loaded save
![On Loaded Save with Enough Phosphate and Ammonia to Evolve,  Phosphate Not Allocated to Evolution Bar, But Stored Instead](https://user-images.githubusercontent.com/44108929/97807076-65f6b700-1c24-11eb-8d53-e3a8bb7f48de.png)

Unable to click evolve when adequate phosphate and ammonia reached.
![On Loaded Save with Enough Phosphate and Ammonia to Evolve, Evolution Is Not Clickable When Adequate Levels of Phosphate Reached](https://user-images.githubusercontent.com/44108929/97807020-1e702b00-1c24-11eb-99e9-9e2d89d7d486.png)

The save file in-question which should begin with a full evolution bar of ammonia and phosphate and almost no stored resources of either.
[Patch Map Report Population Discrepancy.zip](https://github.com/Revolutionary-Games/Thrive/files/5471193/Patch.Map.Report.Population.Discrepancy.zip)

Hope this helps highlight related issues.

**Comment by hhyyrylainen** [comment]
If you can, could you test out my PR: https://github.com/Revolutionary-Games/Thrive/pull/1741
it should fix the compounds stored inside organelles towards division progress not being saved.
The editor button not working after a load is a separate issue: https://github.com/Revolutionary-Games/Thrive/issues/1351

Also, instead of playing the release candidate, you should play the 0.5.2 release version as there are some further changes in that compared to the RC.

**Comment by Aquasheep3000** [comment]
I tried to clone 1741 to test, but when I import into Godot all the asset files fail to load. I don't know how to manage projects, so this is as much as I can help.

**Comment by Aquasheep3000** [comment]
I cannot, but thank you for responding to my bug reports. Wish you well.
