### ISSUE TITLE
Background doesn't work correctly in really wide aspect ratio

### ISSUE THREAD

**Issue by FuJa0815** [Revolutionary-Games/Thrive#1771]
On ultrawide monitors you can see bars on the left and the right when zoomed out far enough
Tested on a 2560 x 1080 monitor

![grafik](https://user-images.githubusercontent.com/30809803/97307092-8ce96d80-185f-11eb-95a9-1ee6048cba16.png)

**Comment by hhyyrylainen** [comment]
I think it's a problem with the background plane not being big enough. So to fix this that plane needs to be made like double the size *and* the shader for it needs to be adjusted so that the image is not stretched more than it is currently.
Here's screenshot when you go even wider:
![2020-10-27_15 42 35 9279](https://user-images.githubusercontent.com/3796411/97309897-46017500-186b-11eb-9fb1-a9ded075f7c9.png)
