### ISSUE TITLE
Incompatible save dialog not loading save on confirm

### ISSUE THREAD

**Issue by Kasterisk** [Revolutionary-Games/Thrive#1820]
Instead it just closes the dialog, might just be the confirm signal for it is not connected to the code

**Comment by hhyyrylainen** [comment]
Could you confirm *which* dialog? The incompatible dialog with just an "OK" button is not meant to allow loading the save. But the dialog for different version number and broken game, *are* meant to allow loading.
The known incompatible is disallowed because I do not want any bug reports about loading saves that are 100% broken because I changed the save format so much.

**Comment by Kasterisk** [comment]
Oh woops, yeah I mean the incompatible save dialog, didn't know that's intended, this issue could be closed then.
