### ISSUE TITLE
Various not translateable strings

### ISSUE THREAD

**Issue by FuJa0815** [Revolutionary-Games/Thrive#1835]
Here is a collection of non translateable string I found, that should be translateable:
- [x]  At Cursor
![grafik](https://user-images.githubusercontent.com/30809803/99189906-e7416400-2763-11eb-96a2-adb1a1d73a9e.png)
- [x]  years
![grafik](https://user-images.githubusercontent.com/30809803/99189943-1952c600-2764-11eb-8edf-249fe1900d18.png)
- [x]  CURRENT LOCATION
![grafik](https://user-images.githubusercontent.com/30809803/99189970-4a32fb00-2764-11eb-9b77-0e4febe38564.png)
- [x]  second (ignore everything else being english)
![grafik](https://user-images.githubusercontent.com/30809803/99190194-7dc25500-2765-11eb-80e3-96d051b88535.png)
- [ ]  on/off
![grafik](https://user-images.githubusercontent.com/30809803/99190220-9c285080-2765-11eb-8507-b8b0748328e0.png)
- [x]  Save type (AutoSave, this need more work because its just the enum toString)
![grafik](https://user-images.githubusercontent.com/30809803/99190282-f1646200-2765-11eb-92e9-7c7f96b1313e.png)
- [x]  ConfirmationDialog buttontext (I think thats godot controlled and not that easy to change)
![grafik](https://user-images.githubusercontent.com/30809803/99190311-21136a00-2766-11eb-9c16-bc50b4f3ac2a.png)
- [x]  TIP: press the undo button in the editor to correct a mistake (the tips do get translated, but the tip in the loading menu does not. I only got this one tip in the loading screen, shouldn't it be randomized? The tips in the help menu are randomized.)
![grafik](https://user-images.githubusercontent.com/30809803/99190405-b0b91880-2766-11eb-87d2-fe25cd7a8744.png)

**Comment by hhyyrylainen** [comment]
"on/off" is from an inbuilt Godot widget, we probably can't change that. (unless the same approach as for ConfirmationDialog works that I mention below)
And you are probably right about the "ConfirmationDialog" text, though maybe if we add "OK" and "Cancel" into the translation files, they might work (though that needs an explicit allow in the formatting check script as it probably otherwise complains).

**Comment by FuJa0815** [comment]
defining OK and cancel in the translation files works, I've just tested it.
defining ON and OFF does not seem to work

**Comment by hhyyrylainen** [comment]
Those "ON" and "OFF" are probably image files, at least I think so because they look blurry at 4K, if I remember correctly.

This is the place where "Cancel" needs to be ignored: https://github.com/Revolutionary-Games/Thrive/blob/7a6e4e287c1f37b107781229fece18cdb4cddda9/check_formatting.rb#L370 for formatting check to succeed.
If you have the time, could you make a PR out of that? It should be pretty short and simple.

**Comment by hhyyrylainen** [comment]
One more thing I thought off, there probably needs to be some method added to MainMenu class like `CallRandomTranslationServerStuff` that calls TranslationServer.Translate("Cancel"); etc. to make sure those are picked up in the translation template. Otherwise I think it will be difficult to put OK and Cancel in some sensible place that is picked up to be translated.
