### ISSUE TITLE
When rebinding key it gets immediately triggered after confirm

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1903]
bug in rebind, immediately it considers the action pressed, for example add a new key to "Toggle FPS" and see the FPS get toggled immediately.

**Comment by turoni** [comment]
I did some investigation and I think I have possible solutions (exact implementation of those tbd).

InputEventItem.cs is a node and handles the _Input for the rebinding
InputManager.cs is another node that seems to forward the _Input to all attributes among which onKeyPressedDown.

1st solution:
InputEventItem has a WaitingForInput bool. If we can do an early return on WaitingForInput in the InputManager the bug should 
be solved.
Potential issues: 
- I'm not sure InputManager can "see" InputEventItem
- This feels kind of like a hack

2nd solution:
Both are node's that get send the InputEvent from godot.
If we can "consume" the InputEvent in InputEventItem it shouldn't be send to any other nodes.
Potential issues: 
- SceneTree does not seem to have a set_input_as_handled() function as indicated by the documentation
- I'm not sure if there is an order to the nodes and InputManager may come before InputEventItem can consume it.

Since I am completely new to C# and godot I thought it best to get some advice before continuing.

**Comment by hhyyrylainen** [comment]
Removed the help wanted tag as that is for issues that we on the team need help with from some helpful outsider.
