### ISSUE TITLE
Disallow quick save in microbe stage before loading is finished

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#1909]
make MicrobeStage QuickSave() not allow quicksaving before stage is loaded and potential autosave is complete

**Comment by turoni** [comment]
I am going to attempt this as my first issue in thrive on godot.
The assumption I am making is that the stage being loaded means starting a new game or opening a save.
Or should this also include switching from Editor to Microbe stage?

**Comment by hhyyrylainen** [comment]
It does also include when switching back from the editor. 
The stage already has a property "TransitionFinished" that goes true once the fade from black into the stage is finished.

**Comment by turoni** [comment]
Aha, that makes things easier.
I also think checking on a potential autosave being in progress should be checkable by the InProgressSave object.
Is there a way to see if one of these exists? Following the constructor I don't see it being registered anywhere.
Is this something that needs to happen, happens because of some annotation magic or in another way I am unfamiliar with?

**Comment by hhyyrylainen** [comment]
The auto save blocks the game loop so, if your newly added code is running, then auto save isn't in progress.
