### ISSUE TITLE
Provide feedback on enter press after writing cell name

### ISSUE THREAD

**Issue by RacerBG** [Revolutionary-Games/Thrive#2011]
**Describe the bug**
1. After renaming the cell to something other than the default name when pressing Enter the **| beam** does not disappear even though the name itself is saved. This could be confusing because it leads to the impression that the new name is not saved.

**To Reproduce**
1. For bug # 1 -> Try to rename the cell in the Microbe Editor.

**Expected behavior**
1. For bug # 1 -> After pressing Enter or the box loses focus the | beam should disappear.

**System info (please complete the following information):**
- Thrive version [0.5.3.0 RC1]

**Comment by hhyyrylainen** [comment]
> After renaming the cell to something other than the default name when pressing Enter the | beam does not disappear even though the name itself is saved. This could be confusing because it leads to the impression that the new name is not saved.

I'm pretty sure that's just because there's no callback or anything when you press enter on it. The new species name is saved immediately each time you enter or remove a character from the text box.

I suppose it would be possible to make it so that pressing enter (when the name is valid) would defocus the text box giving the player that it was accepted.

@Kasterisk any thoughts on that? Is that possible to make?

> At the cursor shows Nothing here when it is above the player's cell or above the floating toxins, or above any dead cell remains (I have not tested this above bacteria though).
Not showing the player's own cell is intentional. Not sure if that should be changed. I think at some point I had it say "you" or "your cell" but that got removed.

Other than that, that issue is a duplicate:
https://github.com/Revolutionary-Games/Thrive/issues/1710

**Comment by hhyyrylainen** [comment]
https://github.com/Revolutionary-Games/Thrive/issues/2012

I'll rename this issue to be about providing feedback on "accepting" a new name in the editor.

**Comment by Kasterisk** [comment]
> @Kasterisk any thoughts on that? Is that possible to make?

Yeah, it should be possible, I saw LineEdit has a `text_entered` signal, I think we could use that.
