### ISSUE TITLE
Display Compound Storage as %

### ISSUE THREAD

**Issue by RacerBG** [Revolutionary-Games/Thrive#2201]
**Describe the bug**
The current implementation of the compound storage amount is functional but it looks a little out of place with the usage of plain integers which are supposed to show the amount of every compound which the cell collects.

**Expected behavior**
Instead of displaying 2/4 or 0/4 the compounds could be displayed with a % value between 0% and 100%. For example:
**4/4 -> 100%
2/4 -> 50%
0/4 -> 0%**
...

Regards,
Georgi

**Comment by hhyyrylainen** [comment]
If we moved to percentages, you wouldn't actually see how much you have, that makes it not possible to really know how long your stores last, how much towards the next evolution you have etc. I've asked for comments from other team members, but if they aren't very positive, I'll close this.
This is more of a design choice than a technical issue, so github isn't the right place for this kind of a gameplay change suggestion.

**Comment by RacerBG** [comment]
> If we moved to percentages, you wouldn't actually see how much you have, that makes it not possible to really know how long your stores last, how much towards the next evolution you have etc. I've asked for comments from other team members, but if they aren't very positive, I'll close this.
> This is more of a design choice than a technical issue, so github isn't the right place for this kind of a gameplay change suggestion.

No problems. :smiley:

**Comment by ender-titan1** [comment]
Just an idea but maybe we could make percentages toggleable in the settings so it could display both or normal integers only for people who find percentages useful.

**Comment by hhyyrylainen** [comment]
People often suggest that "why not both?" but the issue with that is that in order to make sure that both options work, someone needs to regularly test the game with both of the modes and that's pretty difficult to enforce (for example the tutorial, which I often play without, has broken in the past because *I* haven't tested it, and I'm already busy enough). Then there's the second point where the code burden to update existing code for new features gets worse for each added variant that needs to be supported.

**Comment by hhyyrylainen** [comment]
I got two replies from the dev team, both agreeing with me, so I'll close this as not a feature we want. Feel free to discuss on the community forums or the discord about this feature, though.
