### ISSUE TITLE
Hide placed cell graphics in editor when not on the cell editor tab

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#2269]
**Describe the bug**
As you can see, the cell is visible on Report page. Is that working as intended? It looks a little weird.

**Expected behavior**
Maybe it should be hidden outside the Editor page.

**Screenshots**
![image](https://user-images.githubusercontent.com/60734649/120072908-9de5b000-c0c8-11eb-9dd4-62e6c132e372.png)

**Comment by Kasterisk** [comment]
It has been that way since the 0.4.x versions so most likely intended(?) or could just be a technical limitation from the old engine that carries over to the subsequent releases. Frankly I never questioned this myself, personally I'm also in the opinion of only showing the models while in the editor tab.

**Comment by hhyyrylainen** [comment]
I can accept if someone wants to bother with the additional complexity of needing to hide the already placed cell parts graphics based on the editor tab.
