### ISSUE TITLE
Replace the Main Menu music and adjust some volume multipliers

### ISSUE THREAD

**Issue by Oliveriver** [Revolutionary-Games/Thrive#234]
The current music for the Main Menu needs to be replaced with this: https://www.dropbox.com/s/ee91gqqvji3nd1e/Thrive%20Main%20Theme%20v2.ogg?dl=0

Also, some of the volume multipliers in the scripts have been changed to highlight the sound effects as they were being created. I'd imagine the Microbe Stage, Editor and Main Menu music should be at full volume, with ambience and sound effects slightly quieter.

**Comment by Lepticidio** [comment]
I don`t have much idea about programming, but i have been looking around and I found this part of the script code:
    soundSource.volumeMultiplier = 0.12
    ambientEntity:addComponent(soundSource)
    -- Sound
    soundSource:addSound("microbe-theme-1", "microbe-theme-1.ogg")
    soundSource:addSound("microbe-theme-3", "microbe-theme-3.ogg")
    soundSource:addSound("microbe-theme-4", "microbe-theme-4.ogg")
    soundSource:addSound("microbe-theme-5", "microbe-theme-5.ogg")
    soundSource:addSound("microbe-theme-6", "microbe-theme-6.ogg")   
    soundSource:addSound("microbe-theme-7", "microbe-theme-7.ogg")   
    local ambientEntity2 = Entity("ambience2")
    local soundSource = SoundSourceComponent()
    soundSource.volumeMultiplier = 0.4
    soundSource.ambientSoundSource = true
    ambientSound = soundSource:addSound("microbe-ambient", "soundeffects/microbe-ambience.ogg")
    soundSource.autoLoop = true
     ambientEntity2:addComponent(soundSource)
    -- Gui effects
    local guiSoundEntity = Entity("gui_sounds")
    soundSource = SoundSourceComponent()
    soundSource.ambientSoundSource = true
    soundSource.autoLoop = false
    soundSource.volumeMultiplier = 1.0

After this issue was opened, the changes made to this part of the code (according to History) were not about that. It seems that I just have to change the namber in volumeMultiplier = 0.4 to the value that is desired. And the main menu music problem can be solved with only changing the name of the source file to the previous one, or, by changing this part of the code:

soundSource:addSound("main-menu-theme-1", "main-menu-theme-1.ogg")

I guess that crovea and moopli already know all that, and they are just doing more difficult things first.  However, just for seeing another milestone issue closed, I could do it now if you say me how i can upload here the changes I make. I have "cloned" and "forked" the code, but I don't know what to do next. If I learn how to use this, I could help with other easy issues. Could anyone explain it to me?

**Comment by Oliveriver** [comment]
Yeah, I think it's almost that simple - I just put this up to make sure it isn't forgotten.

**Comment by jjonj** [comment]
It's not completely straightforward to get changes on the official repository if everything is new to you. You would need to fork -> clone -> create a "branch" -> do the change -> commit -> push -> open a pull request here with your branch. Reading up on git would be the way to go about it!

> and the main menu music problem can be solved with only changing the name of the source file 

You would also need to commit the new music file to SVN (our assets)!
