### ISSUE TITLE
Auto-evo results text doesn't react to language change

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#2785]
![image](https://user-images.githubusercontent.com/60734649/142709275-d0a55efd-1372-4a45-a4b7-5420c89a0acc.png)

**Comment by hhyyrylainen** [comment]
Do you mean the text after "Auto-evo results:" ?
If so, that's an issue known to me, but at least immediately I can't find an existing issue (I found this: https://github.com/Revolutionary-Games/Thrive/issues/1996 but it's about the format of the auto-evo results).

So basically the problem is that the auto-evo results are converted into a descriptive string *once* and then the results are applied. So to make that text react to language change the info needed to build it needs to be cached somehow so that the text can be regenerated.
