### ISSUE TITLE
Godot doesnt update the Transform.Basis of MovementComponent

### ISSUE THREAD

**Issue by Kemikal1** [Revolutionary-Games/Thrive#2906]
**Describe the bug**

Aparently Godot doesnt update  the Transform.Basis of MovementComponent unless checked with an if or another condition

**To Reproduce**
Dont check the transform.basis with a condition
SEE MovementComponent.cs line 60
**Expected behaviour**
the transform.basis shouldnt update when checked.

**Comment by hhyyrylainen** [comment]
Based on the description I'm wondering what's going on here. Because I just looked at profiling information and was able to see that Godot waits until transforms are needed to compute them, as it is very expensive to recursively compute the final transform. Just an observation, but it might be related.

**Comment by Kemikal1** [comment]
Huh, well i guess this isnt really an issue then.

**Comment by hhyyrylainen** [comment]
Still weird that our code *wouldn't* work correctly unless we force some transform to be computed early...

**Comment by Kemikal1** [comment]
Thinking a bit more about it then that means that whenever you change a transform the object wouldnt move unless the Transform is called??? Yea still weird.
