### ISSUE TITLE
Cytoplasm "organelle"

### ISSUE THREAD

**Issue by Moopli** [Revolutionary-Games/Thrive#291]
A new organelle, which:
* can be replaced by other organelles
* costs a small amount of MP
* performs glycolysis

All organelles should perform a small amount of glycolysis, scaled by the number of hexes they take up.

**Comment by Untrustedlife** [comment]
it should do some glycolysis. Just far less then a mitochondria according to the GDD, it should also strore compunds (again, far less then the vacules) as-well because of the GDD.

**Comment by Untrustedlife** [comment]
updated my comment*

**Comment by Moopli** [comment]
Also make all organelles able to perform a small amount of glycolysis, scaled by number of hexes they take up (since they all sit in cytoplasm)

**Comment by Oliveriver** [comment]
@jjonj @TheCreator-- 

Are you planning the simple route of just adding a cheap blank organelle that just adds size to the cell and consumes small amounts of ATP, or are you going to have it be a base organelle which needs to be placed before adding others? My thinking is that the latter might be too complicated a concept for players to handle until we get a tutorial or better GUI in place, but the former doesn't serve much purpose.

**Comment by TheCreator--** [comment]
Well, I still don't see a purpose for cytoplasm organelles, so I'm just going to do what you guys tell me to do :p

But I think we could allow the player to do both. If you place a mitochondrion on cytoplasm, you pay 25mp, on the other hand, if you place it on a place without cytoplasm, you automatically purchase 2 cytoplasm tiles and pay 45. I also believe we decided against cytoplasm consuming ATP, since it can easily make it out of glucose through glycolysis. Finally, the only thing cytoplasm should effect is acceleration, (because F=ma and flagella produce a constant force).

I'm leaving this decision up to you guys.

**Comment by TheCreator--** [comment]
Fixed with #397
