### ISSUE TITLE
Add species cap in auto-evo as a performance parameter

### ISSUE THREAD

**Issue by Maxonovien** [Revolutionary-Games/Thrive#2944]
So that this performance-driven game limitation can be better adapted to different setups with different performance capacities.

**Comment by hhyyrylainen** [comment]
This is actually a bit difficult as we need to consider what happens if the player wants to change the cap after starting a game, and what happens if someone loads a save made by a person who has a different cap. They will anyway struggle to run the auto-evo at least once in that case / the save they load is more devoid of things they expect.

**Comment by Maxonovien** [comment]
Hmm, technically, changing the cap during the game will only cut sharp in the world life after the next auto-evo (or offer more space for it). However, if this cap is computer-specific and a save is exchanged, it would indeed potentially bring surprising results.

**Comment by hhyyrylainen** [comment]
This *could* theoretically also be a world specific option, but that complicates changing it as it needs in the options menu to show a separate control (like for tutorials) for the current game to change the value per game and per computer default (or it could be a new game option to select how fast your computer is).

**Comment by hhyyrylainen** [comment]
The new auto-evo removed the force extinction system so a hard species cap seems like something we've moved even further away from so I'll close this issue as probably outdated.
