### ISSUE TITLE
Issues when running low fps

### ISSUE THREAD

**Issue by jjonj** [Revolutionary-Games/Thrive#303]
At lower fps (1-10) you can notice the player microbe having a speedhack effect.

At very low fps (<1) emitters stop emitting

**Comment by Moopli** [comment]
The best way to solve this would be to split the physics and graphics loops. That will be difficult without a heavy redesign of the core of the engine, to change how systems get scheduled. 

@Nimbal

**Comment by jjonj** [comment]
We did that already! :P logicTime and renderTime It's simply not being used properly somewhere

**Comment by Moopli** [comment]
Actually, that doesn't do it. Each system still runs in synchronous order, meaning one slow System will delay the others, and thanks to the timing tricks we use, they will compensate for the delay by simulating a larger step. This is exactly the problem.

**Comment by prshreshtha** [comment]
In games that I've made, I've always used a separate thread for physics and had rendering on the main thread, it worked very well, the physics timestep was 5-10 ms regardless of fps. I've never tested it with a single-core computer though.

**Comment by Moopli** [comment]
@prshreshtha, well yes, that's the standard gamedev best practice. Even on a single-core, unless you do something terribly wrong with your threading, it should work out well. 

What we need to do is overhaul our system-synchronization code to be parallel. We will *definitely* need to be able to run systems fully asynchronously once we get to later stages (so we can do preloads, background computation, variable simulation LOD, etc). We'll need to able to do more than that, actually, since a lot of systems have certain ordering dependencies (which is another problem of its own, since ordering dependencies are currently implicit and found through trial & error). 

Ideally, each system would be annotated with the minimal number of constraints that must be met for it to run (most importantly, what systems must run before). We enforce no circular dependencies, since otherwise the scheduling problem is much less tractable. We're left with a DAG (directed acyclic graph) that describes the order in which systems must run during one game update cycle. We might end up with several DAGs, each of which could have different requirements for when it runs -- those would just be other constraints on certain nodes of the DAG in question.

Then, when we want to optimize, we can look at each DAG, see how interconnected they are, and try to split them into more independent streams.

**Comment by jjonj** [comment]
> http://gafferongames.com/game-physics/fix-your-timestep/

This is what we're doing, no? I remember reading that article many years ago

Decoupling physics is as easy as a compile flag I believe, not sure whether we have it running or not.

Another unrelated optimization that fits very well with the entity component is allocating components in sorted memory blocks to heavily reduce cache misses

**Comment by Moopli** [comment]
No it's not -- what we're doing is the kinda-good-thing that the article mentions, but not the correct way which the article is arguing for. A decoupled system can run at an exact interval, meaning you can avoid worrying about delta-t. Speedhack effects happen when lag causes the per-frame delta-t to rise high enough that the physics system moves the speedhacking object too far. I'm not sure about the emitter thing, but I am quite sure it's part of the same problem with large delta-t.

There problem, essentially, is that a system of discrete updates (position updates, compound-calculation updates, etc) can't work perfectly with continuous time. There are two solutions: fix timesteps, thus making time essentially discrete; or do lots of substepping, effectively increasing your discrete update time resolution. Substepping doesn't solve everything, but it can make things better. Some systems we have currently do a bit of substepping, with substep number scaling with delta-t.

**Comment by prshreshtha** [comment]
I've gone for the simple route myself, and it seems to work independent of FPS:

```
std::thread update_thread{ &_internal_update, this };
update_thread.detach();

// render loop here
```

The render loop and update loop each have their own clocks to maintain time. To check if both loops are to be ended, I used an atomic bool.

This approach completely separates the two loops and they don't place any restrictions on each other. Performance hasn't been an issue for me.

**Comment by hhyyrylainen** [comment]
This needs to be verified once the engine_refactor is complete.
