### ISSUE TITLE
Spawns can pop in on screen when near the entity limit

### ISSUE THREAD

**Issue by Oliveriver** [Revolutionary-Games/Thrive#3441]
Items (clouds, microbes, chunks) can spawn in the player's view when near the entity limit, creating a very visible pop-in. I've even had issues where iron chunks appear right in front of me as I'm moving, stopping me in my tracks.

I suspect this has something to do with queued spawns waiting until we drop below the entity limit (or maybe the max spawns per frame limit?) to spawn, but by that time the player might have moved to the sector that was being spawned. Maybe it's best to just ignore such spawn attempts if they're too close to the player?

**Comment by hhyyrylainen** [comment]
The explanation makes sense to me. I guess the simplest and most robust fix would be to make it so that the queued spawns method would check if the thing it just spawned is too close to the player, and if it is it would despawn it(or skip adding it to the world depending on which one is easier). And after that it should probably discard rest of that spawn as other entities that might still be in it, would also have a high chance of being too close to the player. Shouldn't be that difficult to implement.
