### ISSUE TITLE
Add a button to eject all engulfed things

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#3583]
so that the player is not stuck getting no glucose. Also would give attentive players a chance to eject a toxic cell they engulfed.

Needs an icon for the hot bar

**Comment by Kasterisk** [comment]
I have an idea for a more difficult but flexible system. Instead of a simple eject all button, we could have the process panel lists all the foods being digested and for each food it gives you the option to expel it, it could also even show the digestion progress with a progress bar. I think this makes sense because digestion is technically one of cell's "processes".

Rough mockup:
![2022-07-26_23 09 37 3370](https://user-images.githubusercontent.com/54026083/181060430-05a8b741-bbd1-489f-b095-8a26554e552e.png)

**Comment by hhyyrylainen** [comment]
I think for that kind of feature to be useful that would also need to show the compounds the player is getting, because otherwise they might as well just have to eject all as they won't know what things have glucose (that's the most common complaint about not getting any glucose and not being able to start ingesting anything new).

**Comment by Kasterisk** [comment]
Might need to have a segmented bar as the progress bar, each segment could show how much compounds left in it.

**Comment by hhyyrylainen** [comment]
The graphics for this button is now done: https://dev.revolutionarygamesstudio.com/files/Asset%20development/Icons/Engulf_Eject_Icon.png
