### ISSUE TITLE
RfC: Binding agent terminology and in-game information

### ISSUE THREAD

**Issue by schnautzr** [Revolutionary-Games/Thrive#3612]
I recently proposed a change to the locale that was met with uncertainty, so let's discuss.

I did some research, and as best I can tell, Thrive's current binding agent appears to work the same way that amoebas are known to work. Here's a crash-course for you.

At the most basic level: Certain unicellular organisms are known to use a binding agent to themselves sticky and join together to form a larger pseudo-organism, which is capable of either breaking apart again or actually altering the functions members of it carry out.

Since Thrive uses a lot of biological terms, it seems appropriate we do so. Let's explore what's actually happening here:

The organisms in question are amoebas belonging to a group known as slime molds. The amoebas release a pheromone called acrasin, which is an adhesive signaling compound which causes other amoebas to adhere to them. The colonial structure they form is known as a grex or slug (depending on the literature). The grex functions as a unit and may either break apart again or differentiate (meaning the individual members become altered such that they carry new functions). It is thought that this is one way that multicellular organisms evolved. As far as I can tell, scientists haven't identified yet how or where the acrasin is produced.

This being the only LAWK version I can identify of a "binding agent", I'm proposing we:

**Add relevant scientific information in the locale files to help users understand what is actually happening here, because as it is, it appears we're just having the cell make glue or something, which feels really silly without any informational background.**

**Comment by RacerBG** [comment]
> Add relevant scientific information in the locale files to help users understand what is actually happening here, because as it is, it appears we're just having the cell make glue or something, which feels really silly without any informational background.

Rest assured that I read your entire post but I will quote only this sentence for a few reasons:

1. Thrive is a scientific game but it's still a game. If we try to make everything to look real and explain it in great detail as you suggest, it won't be fun. The playerbase ranges from kids to biology scientists (probably) and we can't make everyone happy but there needs to be a balance.
2. It's not a deal breaker if the current system remains because Thrive already have a few compromises, the biggest example is the naming of "OxyToxy NT" and the cloud system for which a good discussion developed here: https://forum.revolutionarygamesstudio.com/t/revamping-compound-clouds/913/15
3. Players hate to read. Literally.

In my opinion the current descriptions are serving the game just fine but I'm not against making the game more scientific, don't get me wrong.

**Comment by hhyyrylainen** [comment]
We some pretty long flavour texts on some of the organelles so expanding the binding agent's flavour text would be good. In fact the binding agent currently has no scientific flavour text because it is one of the newer organelles and our organelle theory writers have been inactive (though I did get one recent new organelle flavour text written for but it took a lot of prompting from me).

**Comment by nickthenick** [comment]
As HH said, the lack of flavour text for Binding Agents is true, we do need to fill that in. 

In terms of replacing the name for Binding Agents, it's true that the term Binding Agent was invented by us and is not used by scientists. However, as far as I know, Acrasin is simply the name of a specific protein used by slime moulds, and is not actually the general term for such proteins either. 

The most accurate term I know of would be "Adhesion Proteins": https://www.google.com/search?client=firefox-b-d&q=adhesion+proteins

In terms of replacing the name Multicellular Colony with the term "Grex", again as far as I know Grex is a term specific to Slime Moulds and is not a common name for such a phenomenon. Furthermore, Multicellular Colony is actually not a term invented by us, "Colony" and "Colonial Organism" are terms used by scientists to refer to simple multicellular organisms (with low levels of differentiation): https://en.wikipedia.org/wiki/Colony_(biology)

**Comment by schnautzr** [comment]
I'd be fine with simply adding flavor text, no real reason to change established names right now.

https://en.wikipedia.org/wiki/Acrasin

https://en.wikipedia.org/wiki/Grex_(biology)

https://en.wikipedia.org/wiki/Multicellular_organism#Origin_hypotheses

Also searching on JSTOR for acrasin returns several results.

**Comment by hhyyrylainen** [comment]
I opened a separate issue about the missing flavour text: https://github.com/Revolutionary-Games/Thrive/issues/3613
