### ISSUE TITLE
Allow the player to close the Environmental Variables tab

### ISSUE THREAD

**Issue by nickthenick** [Revolutionary-Games/Thrive#3693]
![image](https://user-images.githubusercontent.com/110012298/184272832-507867db-b934-4c0b-835d-f3c30170ffd7.png)

Considering that the environmental variables rarely change between patches if ever, and the player can also change them in the editor, we should add the ability to close the tab and reopen it. Either by pressing its button on the bottom left, or by adding an X button to it.

Allowing the player to close this tab will free up a lot of valuable screen space.

**Comment by hhyyrylainen** [comment]
Note that the test tube icon is for opening the process panel, so there needs to be an extra button if the C button which hides compounds and the environment is not suitable.

**Comment by nickthenick** [comment]
Ahhh okay that's true, yeah so this issue entails also adding a new button.

**Comment by hhyyrylainen** [comment]
I'll add this to the graphics tasks then as this'll need a new icon.

**Comment by camilomcatasus** [comment]
I'm working on this right now, should the compound button still hide and show the agents panel? I can either create individual animations for each panel (so that each can be hidden or shown individually) or just one for environments and group compounds and agents in another vertical group.

**Comment by nickthenick** [comment]
Oh awesome! Do you want to take over this task? I'm loaded with a lot so won't be able to tackle this for a while.

Hm, I would imagine the best thing to do would be to allow the environmental variables, compounds, and agents tabs to all be closed separately, to allow the maximum customizability of the interface by the player. Let me double check with the team.

**Comment by nickthenick** [comment]
Just checked with the team. Have the compounds and agents open and close with the current button, and just split off Environmental Variables so that it opens and closes with a separate panel.

**Comment by hhyyrylainen** [comment]
Separate button you probably meant to say.

**Comment by camilomcatasus** [comment]
Yeah, I would like to take it over if I'm not overstepping :P

**Comment by camilomcatasus** [comment]
https://user-images.githubusercontent.com/46833522/187794477-b13a8799-2108-46a0-a0a9-80760ce79721.mp4

![multicellular_enviornment_button_demo](https://user-images.githubusercontent.com/46833522/187795819-f2b2e743-85f2-48c3-84eb-57a2d4131fdb.gif)

This is what I have so far. It would be in my branch if my local repository wasn't giving me problems fetching from or uploading to github. Regardless, currently I have two animators so that each panel can be animated separately (with only one the animations pause mid animation), however there are still race conditions when both buttons are pressed within a short period of time. 

I'm asking for feedback in what to do. If it's fine as is or if I should try to fix them. I could try to queue the animations if Godot has a system for that. 

I was also wondering if the popping up and down was desirable or not. If the current animation was replaced with a growing animation (where the rect_size grows to its normal size from 0), there would be no popping or snapping of the panels.

**Comment by hhyyrylainen** [comment]
I think that animation looks good enough. The only thing I'd change is the font on the "E" to be consistent with the "C".

**Comment by camilomcatasus** [comment]
I couldn't find the font for the button written down anywhere in the docs or the wiki :P, if you guys let me know what the font name is I'll go make the button. 

In the meantime I tried looking for a font that is close enough to the C and came up with these:
![environmentButton](https://user-images.githubusercontent.com/46833522/188195716-027bf740-a14b-4bd5-8334-62380602e743.png)
![environmentButtonActive](https://user-images.githubusercontent.com/46833522/188195722-1edb3a16-eedf-45b3-a124-06bb7b85915f.png)
![environmentButtonHover](https://user-images.githubusercontent.com/46833522/188195767-88c8bc3c-df8f-4b77-adc2-a1b715b64fee.png)
![compoundsButton](https://user-images.githubusercontent.com/46833522/188196690-531eb296-2449-461b-9304-65e47d59b447.png)
(Compound button for comparison)

Also have some other environment button ideas I mocked up(not final if these other ones would be preferred). 
Petri Dish:
![petriEnvironmentButtonActive](https://user-images.githubusercontent.com/46833522/188195937-9cc112a5-b68c-4e62-8b40-aaa87665e97d.png)
![petriEnvironmentButtonHover](https://user-images.githubusercontent.com/46833522/188195938-bca41b2c-b005-4855-95bc-7e535fd84ce7.png)
![petriEnvironmentButton](https://user-images.githubusercontent.com/46833522/188195939-cce3f630-fca6-41c8-b593-30b129952caf.png)
World:
![worldEnvironmentButtonHover](https://user-images.githubusercontent.com/46833522/188195998-cb44d3ee-ca6f-46df-8c34-1da9d9a843fc.png)
![worldEnvironmentButton](https://user-images.githubusercontent.com/46833522/188196001-6aff151f-4fb8-412c-9c79-5d78ea5bbae2.png)
![worldEnvironmentButtonActive](https://user-images.githubusercontent.com/46833522/188196002-33ca6a19-a36a-4c1e-95d1-29014a8d3f76.png)

Last thing is that I figured out the problem I was having with github. I don't think I can upload png files with git because of git lfs? If I apply to the dev team and get accepted this won't be a problem, but for now I'd have to ask someone on the dev team to upload the images right?

**Comment by hhyyrylainen** [comment]
It'd probably be better to redo the C button with either Lato or Jura (those are the primary fonts used in the game) fonts so that the E button can then be made match.

**Comment by camilomcatasus** [comment]
I'll get to work on that then

**Comment by camilomcatasus** [comment]
Ok I used Jura and Lato to make like 24 images. Upload whichever one you think is best or let me know if any edits need to be made.

Jura Bold:
![juraBoldE](https://user-images.githubusercontent.com/46833522/188213084-1150cdce-256f-4ee4-a694-7d370067710c.png)
![juraBoldEHover](https://user-images.githubusercontent.com/46833522/188213088-508b878f-3467-4733-9b39-4a0ebe77c969.png)
![juraBoldEActivated](https://user-images.githubusercontent.com/46833522/188213086-222cfa33-0322-4073-af77-359a69576096.png)
![juraBoldC](https://user-images.githubusercontent.com/46833522/188213089-654a3ade-fbdc-4ecd-b2ce-c7507870b9dd.png)
![juraBoldCHover](https://user-images.githubusercontent.com/46833522/188213082-29c8f17f-a47e-4db7-862a-593bc33ac874.png)
![juraBoldCActivated](https://user-images.githubusercontent.com/46833522/188213090-bc6abf9b-b4d1-419d-81fa-853d38a77c1d.png)

Jura:
![juraE](https://user-images.githubusercontent.com/46833522/188213140-53994a04-f6bd-425a-b354-6baa06041108.png)
![juraEHover](https://user-images.githubusercontent.com/46833522/188213133-ffae4947-4954-45bd-bc53-e812bf1942d2.png)
![juraEActivated](https://user-images.githubusercontent.com/46833522/188213141-ab1e1cc8-8058-4341-aedf-b38f81b5d551.png)
![juraC](https://user-images.githubusercontent.com/46833522/188213134-302798bc-8e7c-4dd7-b19d-df739784da87.png)
![juraCHover](https://user-images.githubusercontent.com/46833522/188213139-41c9d750-1dc8-4419-8e39-d7a1fa238604.png)
![juraCActivated](https://user-images.githubusercontent.com/46833522/188213137-c2b67b31-9d6f-49b1-af44-7280f363881f.png)



Lato Bold:
![latoBoldE](https://user-images.githubusercontent.com/46833522/188213230-0b1c2245-15c6-4c75-865d-1a0562cfb3e7.png)
![latoBoldEHover](https://user-images.githubusercontent.com/46833522/188213235-6018d20d-58f3-4c9f-b991-3bf51581ac41.png)
![latoBoldEActivated](https://user-images.githubusercontent.com/46833522/188213231-03bd436f-43a9-4a1f-9468-6fcac04a4a27.png)
![latoBoldC](https://user-images.githubusercontent.com/46833522/188213224-bd4e12c1-f1fc-4599-a6dd-6be6d6d665bc.png)
![latoBoldCHover](https://user-images.githubusercontent.com/46833522/188213229-7fa475fe-66d6-4f0b-b3de-ecf39162443e.png)
![latoBoldCActivated](https://user-images.githubusercontent.com/46833522/188213226-e900977c-08b2-4662-a815-121c84fff934.png)

Lato:
![latoE](https://user-images.githubusercontent.com/46833522/188213186-e52448ad-4a4b-4c13-8b95-92fd7506d93b.png)
![latoEHover](https://user-images.githubusercontent.com/46833522/188213182-aba40bc3-e25f-45a6-8010-ac57b34d44de.png)
![latoEActivated](https://user-images.githubusercontent.com/46833522/188213179-38df79e1-b35b-4197-aac1-a541e445fb66.png)
![latoC](https://user-images.githubusercontent.com/46833522/188213183-f25d5329-2b5f-404e-887c-71b9bfa56f35.png)
![latoCHover](https://user-images.githubusercontent.com/46833522/188213185-0d874c03-0b99-4b6f-aaa8-6298d1b01f7e.png)
![latoCActivated](https://user-images.githubusercontent.com/46833522/188213184-59a586b4-d8dc-4e44-8cfe-74bf8f7d129f.png)

**Comment by hhyyrylainen** [comment]
I think lato bold is the best. I suspect no one else will help you with uploading so I'll have to do it. It'll be much easier for me if you could upload a zip with the files that all have the right names.

**Comment by camilomcatasus** [comment]
will do

**Comment by camilomcatasus** [comment]
[newButtons.zip](https://github.com/Revolutionary-Games/Thrive/files/9480340/newButtons.zip)

**Comment by hhyyrylainen** [comment]
You didn't include the .import settings for the files so I had to set the settings myself for the environment panel (mipmaps need to be on for icons), but I've now committed the assets. https://github.com/Revolutionary-Games/Thrive/commit/1db7b248fe10d0ea7045113cafe974a1b78332f7

**Comment by nickthenick** [comment]
Awesome work with this man! Apologies I was away for some time shortly after you started, but don't worry at all on overstepping it's great to have more helping hands to share the workload. I replaced myself with you as the assignee so you get the proper credit for it. 

I think it would be much preferable to have image-based icons for Environment and Compounds instead of the current letter icons, but I agree that we can separate that from this task, so for now the E and C icons are good. I like what you did with the mockup icons, I'll tag you on the new task that I make for new icons for the Environment and Compounds panels.
