### ISSUE TITLE
Auto-evo configuration is not correctly stored in save.

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#3706]
Due to the fact that AutoEvoConfiguration is an IRegistryType, just internal name is saved.

**Comment by 84634E1A607A** [comment]
My first reaction is to serialize the config as JSON and store it in the internal name.

**Comment by hhyyrylainen** [comment]
Here's my comment on the PR I made which is very related to this:
If the problem is that the auto-evo settings are a registry type, I'd suggest the following refactoring:
- Remake the current class into a base class AutoEvoConfiguration which has the settings in it
- Create a new PredefinedAutoEvoConfiguration class which is a registry type

That should solve the issue as the auto-evo configuration will then be fully serialized and deserialized in the save. Also should probably slap a `[JsonObject(IsReference = true)]` on the base class.
