### ISSUE TITLE
Cells growing in multicellular should not be able to enter invalid engulf state

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive#3802]
![image](https://user-images.githubusercontent.com/60734649/191053445-7035c273-c178-4734-b45e-ac82f2189d78.png)
<- In the image above, 52585 triggered an error print

Steps to reproduce:
1. Add 2 celltypes, Stem engulfable, another not.
2. Enter engulf state and wait

**Comment by hhyyrylainen** [comment]
I'll guess that this happens because when new cells are added through growth, they apply the current colony state to themselves, and for seemingly some reason they enter an engulf state that way when they should. Or does that only print an error? If it only prints an error then we just need a bit of code to ignore the warning in that case, like it is ignored when a colony goes to engulf mode and doesn't let all members enter engulf mode.

**Comment by 84634E1A607A** [comment]
I think this is because engulf state being applied before colony state

**Comment by hhyyrylainen** [comment]
With the ECS changes, cells should now automatically get kicked out of invalid engulf mode. So this bug should be fixed.
