### ISSUE TITLE
Test all controller type icon sets (and controller detection)

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#4013]
I have only a few types of controllers so I can't test that all of these icon sets are correctly in the game (and don't have typos in the icon file names or something like that). Here's what needs testing:
- Xbox360,
- XboxOne
- PlayStation3
- PlayStation4

Also if any of those controllers don't use the right icons, then the controller name detection code needs to be fixed for that controller.

**Comment by matthewpaul-us** [comment]
What do we want to see in terms of testing for these? I hooked up an XboxOne controller, it was detected, and I was able to see the correct icons for the controller. I didn't get pics of all of them or test all of them, as somewhere along picking commits my copy lost the ability to detect the controller.

On running Thrive, here is the controller detection output: `First connected controller is: XInput Gamepad`


Here are bumpers: 
![image](https://user-images.githubusercontent.com/1484070/213899590-319d9bc8-839d-4ce0-8d67-c00190f4ec26.png)

I can also confirm that triggers and left stick show icons. I didn't get a chance to check face buttons due to the controller not being recognized on subsequent runs. I'll keep fiddling with it to see if I can confirm the rest. I also have a playstation 4 controller. If the controller still works, I'll get some testing for that one as well.

**Comment by hhyyrylainen** [comment]
I actually ended up adding an option in the graphics settings to force a specific controller icon set, so testing with different controllers is not really necessary (unless the type detection is incorrect, but that is also a bit limited as it can only use the controller name).

This issue was mostly just for checking that it doesn't happen to be the case that some controller variant of a button has an unexpected filename (and would fail to load because of that). I'll close this as likely working for now, if there are some broken icons after all a separate issue can be opened about fixing them.
