### ISSUE TITLE
Removing a organnele from cell in editor take DNA

### ISSUE THREAD

**Issue by lukaandjelkovic** [Revolutionary-Games/Thrive#404]
If i set organnele, (like Mitochondria), i lose DNA points.
Then when i right click on it (To remove it), i lose DNA points again.
So basically, that should be reverse. I should get my DNA points back when i remove it.
Oooops, sorry @TheCreator-- , i posted it onto GitHub again.

**Comment by TheCreator--** [comment]
Yes. Please make sure to post on the community forums next time. Also, you should really consider reading through the GDD and the past posts on the devblog, because this issue (and a lot of the other ones you've posted) have already been discussed. For this one, deleting an organelle _should_ cause you to lose DNA points because it is a change from the previous generation.

**Comment by lukaandjelkovic** [comment]
BUT @TheCreator--, what if it's just bringed down to cell accidentaly and you back it in the same second? It should take out DNA when it was before the cell had sex.

**Comment by TheCreator--** [comment]
Then use the undo button.

**Comment by Oliveriver** [comment]
That should ideally cost nothing since it's effectively the same thing but right now it's not a priority.
