### ISSUE TITLE
Unable to manually select the screen resolution

### ISSUE THREAD

**Issue by SentryPrimies** [Revolutionary-Games/Thrive#5077]
### Describe the bug

Unable to manually select the screen resolution, t sets the resolution automatically by itself

### To Reproduce

1. Start the game
2. Go to Settings

### Expected behaviour

In early versions of Thrive the screen resolution could be chosen manually, but after switching to godot 4 this is no longer possible.

### Screenshots

![изображение](https://github.com/Revolutionary-Games/Thrive/assets/126711441/9a3540d8-65b4-43b6-90b4-dff397eacdaa)

### System information

- OS: Windows 10
- GPU : Gtx 1050 TI
- Thrive: 0.6.6

### Game Logs

Nothing to display

**Comment by hhyyrylainen** [comment]
> In early versions of Thrive the screen resolution could be chosen manually, but after switching to godot 4 this is no longer possible.

Resolution has not been possible to change since the switch to Godot *3*. Godot doesn't really want to use different window resolutions that can be explicitly set, which is why the setting doesn't exist: https://docs.godotengine.org/en/stable/tutorials/rendering/multiple_resolutions.html

As an alternative we've had a feature request open for a long time to add render resolution / scaling options: https://github.com/Revolutionary-Games/Thrive/issues/1209
