### ISSUE TITLE
mac support

### ISSUE THREAD

**Issue by jtoy** [Revolutionary-Games/Thrive#519]
make it work on mac

**Comment by hhyyrylainen** [comment]
Are you volunteering for this? As the mac support currently stands we have no way of doing it without a mac developer joining the team.

**Comment by jtoy** [comment]
Let me look through the code to see if I could possibly do it.

**Comment by hhyyrylainen** [comment]
We are probably going to switch to unreal engine 4 quite soon. There is already `ue4` branch here on github which you should check out. We had one person try to do a mac build but their computer was too old to support unreal engine.

**Comment by alex-w-k** [comment]
Is the engine just not supported right now on MacOS? I could definitely modify the installer file to work on MacOS.

**Comment by hhyyrylainen** [comment]
The current plan is to keep using Ogre for rendering. Which does support macos, also all of our other libraries also claim cross platform support (everything works right now on windows and linux). But there will most likely be small bugs that need to be fixed and the setup system needs to be modified to add support for homebrew so that it can do a linux style installing of things on mac. So that's why I've been saying we need a competent developer who has a mac.

@alex-w-k which installer file are you talking about? Our releases are currently just zip files with (most) of the required libraries and thrive itself bundled up. It isn't possible to try to run linux opengl programs on mac, right?

**Comment by alex-w-k** [comment]
The installer Ruby file is the installer file I’m talking about. 

It looks like there are OpenGL headers for macOS. 

I’m not super good with C++ or anything like that but I’m decent with ruby and I have a Mac so I can test things and possibly try and learn some as well.

**Comment by hhyyrylainen** [comment]
Well, it would require quite a bit of tweaking to the setup to make sure it can install the right homebrew packages. And then there will probably be tons of compiler errors with the dependencies, which will probably be quite hard to solve for someone without much experience in working with c++. But anyone is of course free to try and if they can get it working I'll accept a pull request or even a .patch.

**Comment by hhyyrylainen** [comment]
I listed some things on our wiki regarding this: https://wiki.revolutionarygamesstudio.com/wiki/Mac_Version
