### ISSUE TITLE
Tutorial and how to play display question marks when movement keybinds rebound

### ISSUE THREAD

**Issue by FunkyDe** [Revolutionary-Games/Thrive#5252]
### Describe the bug

Question marks pop up on movement tutorial prompts (and similar ones like in the how to play menu) when keybinds are changed from standard keys. This issue even occurs with regular movement keys rebound to irregular directions. For example, binding 'Q' to move left produces this issue, as well as binding 'W' to move right.

### To Reproduce

1. Start game as usual
2. Change any movement keybind to anything else (even other keys which would normally have displays, like changing right to W)
3. Question marks pop up on tutorial prompts and similar appearances

### Expected behaviour

I would expect the correct letter to appear in tutorials/prompts for any keybinds rebound, especially for regular keys like WASD.

### Screenshots

![image](https://github.com/Revolutionary-Games/Thrive/assets/96454816/ba30dab0-19d2-475a-8399-40f74ba90403)
![image](https://github.com/Revolutionary-Games/Thrive/assets/96454816/c83c9dae-6321-4fb4-9a67-511d597782f4)
![image](https://github.com/Revolutionary-Games/Thrive/assets/96454816/3b37ba48-116e-4e2d-903a-34318606e50c)
Only changes I made to hotkeys (changed move right for testing's sake)

![image](https://github.com/Revolutionary-Games/Thrive/assets/96454816/efc39a98-ea5c-4494-b507-226d68d83285)
This issue also appears in the "how to play" pop up.

### System information

OS: Windows 11
GPU: NVIDIA GeForce RTX 3060 Laptop GPU
Thrive Version: 6.7.1 (cloned from repo at commit 8cb69ad5715968d7e7581faa109bb5301dcffbfb)

### Game Logs

https://pastebin.com/je471mJY

**Comment by hhyyrylainen** [comment]
I can see the same issue if I rebind the move left default binding to Q (and have some other keybindings there). Looking into the key display logic I see one bug with the handling stopping when it finds a key it cannot load an image for, even if a later key would have an image. 

Our key press icon set is missing a bunch of keys so that'll be much harder to fix (this situation for every key), but I think I can improve things at least somewhat pretty easily.
