### ISSUE TITLE
AI likes to stay stationary (and try to engulf) too much now

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#5423]
Not sure what's caused this but now there are a bunch of cells that don't want to move, and just turn on engulf mode:

![2024-08-28_13 32 54 3979](https://github.com/user-attachments/assets/de3a84a9-4535-4b6b-afff-22b5366b8ad3)

I noticed this when trying to find a new good seed for the microbe benchmark.
This has also been noticed by other people and talked about.

**Comment by dligr** [comment]
(Related: #5364)

It seems like the root cause of this is AI sprinting when engaging prey. I did some testing with AI sprinting turned off ([this line of code](https://github.com/Revolutionary-Games/Thrive/blob/4b8a62d73309edfd0a6723c3d19833a0cfeb383a/src/microbe_stage/systems/MicrobeAISystem.cs#L831)) and the problem was gone.
PR #5357 adds a strain check for this sprinting, which would probably fix the issue (Although I haven't tested this).

**Comment by hhyyrylainen** [comment]
That sprinting PR has some other issues, so just adding the strain check by itself would be a pretty worthwhile PR.

**Comment by hhyyrylainen** [comment]
There's now one attempted fix on this. But it isn't fully sure if this properly and completely addresses this.
