### ISSUE TITLE
Some buttons are not working on self-built version

### ISSUE THREAD

**Issue by arenekosreal** [Revolutionary-Games/Thrive#5444]
### Describe the bug

I am using archlinux and I want to build Thrive myself. After I use [thrive](https://aur.archlinux.org/packages/thrive) to build one myself, the build succeeds, but some buttons in game are not working. Their style changed to indicate they are clicked, but no actual function is invoked.

For example, The `Back` button at `New Game` page, the tab-switching buttons at `Settings` page, The `Undo` button at cell designer, none of them are working.

But this problem just happens on my self-built version, the game at GitHub Release is working normally.

### To Reproduce

1. Prepare an archlinux environment
2. Download the PKGBUILD
3. Run `makepkg -src` in the PKGBUILD's repository
4. Wait for building complete, launch the game, check buttons mentioned before.

You can use this PKGBUILD, it sets `--verbose` flag when calling godot so we can get more detailed output:
[thrive.tar.gz](https://github.com/user-attachments/files/16835531/thrive.tar.gz)

### Expected behaviour

All the buttons are working normally.

### Screenshots

I leave a video here to show what happens:
[video](https://github.com/user-attachments/assets/7f5cae27-748e-4a08-9adc-2cda8b43d2e4)

### System information

- OS: Arch Linux
- GPU: NVIDIA GeForce GTX 1050 Ti
- Game version: 0.7.0.0, but this problem exists on 0.6.x

### Game Logs

[log.txt](https://github.com/user-attachments/files/16835663/log.txt)
Please note that I have to terminate the game because exit dialog's buttons are also not working.
And those `USER ERROR` at last are also found on official version.

### Additional Context

[thrive-0.7.0-3-x86_64-prepare.log](https://github.com/user-attachments/files/16835684/thrive-0.7.0-3-x86_64-prepare.log)
[thrive-0.7.0-3-x86_64-build.log](https://github.com/user-attachments/files/16835680/thrive-0.7.0-3-x86_64-build.log)
[thrive-0.7.0-3-x86_64-check.log](https://github.com/user-attachments/files/16835682/thrive-0.7.0-3-x86_64-check.log)
[thrive-0.7.0-3-x86_64-package.log](https://github.com/user-attachments/files/16835683/thrive-0.7.0-3-x86_64-package.log)

Those are build logs when building with the PKGBUILD provided above, I guess that those `ERROR: Cannot connect to` errors in build.log are the cause, but I am not sure how to fix them now.

Explanation about why I call cmake and godot myself instead using Scripts project: Arch Linux requires their build flags are not changed by cmake, so I use `CMAKE_BUILD_TYPE=None` and set `-DNDEBUG` manually like [here](https://wiki.archlinux.org/title/CMake_package_guidelines#CMake_undesired_behaviors).

**Comment by hhyyrylainen** [comment]
I think this is likely the error that gives some indication as to what is going wrong:
```
ERROR: Unable to open file: res://.godot/imported/default.png-0ecb64421bbeb83f3647ba16f0738ab3.ctex.
   at: _load_data (scene/resources/compressed_texture.cpp:41)
ERROR: Failed loading resource: res://.godot/imported/default.png-0ecb64421bbeb83f3647ba16f0738ab3.ctex. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:274)
ERROR: Failed loading resource: res://assets/textures/gui/cursors/default.png. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:274)
```

Also this seems suspicious:
```
ERROR: Failed to create an autoload, script 'res://src/engine/Invoke.cs' does not inherit from 'Node'.
   at: _create_autoload (editor/editor_autoload_settings.cpp:423)
ERROR: Failed to create an autoload, script 'res://src/engine/StartupActions.cs' does not inherit from 'Node'.
   at: _create_autoload (editor/editor_autoload_settings.cpp:423)
```

Which is maybe an indication that the C# source code was not built. I think Godot should build it automatically when exporting, but a manual `dotnet build` may fix that. 

If I understood you correctly, you are trying to like setup a script to build Thrive from scratch? The usual solution to the above problem is to just open Thrive in Godot Editor and let it sit for a while to import all of the assets. Though that is not suitable for a scripted use-case. Or alternative if you did open the game files in Godot Editor once, the problem might be the editor automatically breaking stuff that needs to be `git reset` away (I'd link you our wiki page here, but our servers are down currently due to hosting provider technical issues). After the initial import the editor should most of the time not break any of the game files automatically, but it is good to check that first whenever some buttons don't work at all in the game.

Our CI builds run in a container (there's a script to create the container in the Thrive repo), and then run the following after cloning the code:

```sh
      - run:
          name: Build with warnings
          command: dotnet run --project Scripts -- check compile
      - run:
          name: Download native libraries
          command: dotnet run --project Scripts -- native Fetch
      - run:
          name: Create builds
          command: dotnet run --project Scripts -- package --dehydrated
      - run:
          name: Upload devbuilds
          command: dotnet run --project Scripts -- upload
```

Which is probably not that helpful, as really the only step you'd need to replicate the build is: `dotnet run --project Scripts -- package Linux --compress false` I added a few flags I think you'd need in your use case.

Our packaging script does a few extra stuff like including info on which commit the game is built from, which is then shown in the options menu, which I think are missing from your script.

**Comment by arenekosreal** [comment]
I don't think so. You can see line 3763 of build.log to find that godot calls `dotnet publish` to build C# part. According to microsoft's [documentation](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-publish#implicit-restore), `dotnet publish` will build the project automatically if needed. After C# part is built, godot will do `savepack` stage, at when those connection failure happens.

As I have explained before, calling cmake and godot manualy instead using Scripts project directly is because that I don't want my custom `CXXFLAGS` being modified by cmake. Actually I am just trying to do package work for my linux distribution, so I have to make build workflow match the distribution's requirements, such as using `-O2` instead `-O3` in `CXXFLAGS`.

**Comment by hhyyrylainen** [comment]
I meant that the code may not be built when the editor starts. And when the editor starts that is when it prepares to load C# as scripts attached to Nodes. It might work like you describe but then Godot would explicitly need to try to reload the editor's script instances after the publish step, which it might not do (because the C# version of the engine has so many extra bugs, I wouldn't be surprised if this was one of those).

> Edit2: As for errors like ERROR: Unable to open file: res://.godot/imported/default.png-0ecb64421bbeb83f3647ba16f0738ab3.ctex, I don't think it is a big problem, because the file will be generated by godot after reimport completed:

I realized after commenting that, this is likely the case as you get those errors anyway when doing a fresh export, so the errors are not serious. Unless you are deleting the source files each time before building, I'd still check that git status doesn't report *any* changes on your local Thrive copy.

**Comment by arenekosreal** [comment]
In fact, exporting game is the first time I start godot in the project. The whole build workflow is run in a systemd-nspawn environment and should finish without interactive operation. So I cannot import in godot editor manually and run export job. I have also tried running `dotnet build -c ExportRelease` before calling godot, but there is no change to the game.

It seems that no modified file is listed in git, the `dist` folder is my custom export directory so it is not included in `.gitignore`
![image](https://github.com/user-attachments/assets/8ceb7db6-701f-408e-aa45-8d44637f0d8e)

**Comment by hhyyrylainen** [comment]
I was about to test doing a build in a container based on the steps you tried, but then I remembered that our website outage (which hopefully won't last too much longer) affects the LFS assets (which are currently unavailable so no new clones can be made).

For reference this is the podman image specification for the environment I would have tried: https://github.com/Revolutionary-Games/Thrive/blob/master/podman/ci/Dockerfile 

So yeah due to that unrelated website problem I cannot test and verify if your build should work with a correctly setup environment or if the build steps themselves need tweaking.

**Comment by hhyyrylainen** [comment]
Okay so our online stuff started working and I did some testing in a container, and I noticed that the builds I made also had the same issue. Even when using the export script. So there is something pretty weird going on I can't figure out.

I plan on updating Thrive to use Godot 4.3 this week. I expect I'll need to investigate this further at least then to make sure builds can be made by our CI system correctly that don't have this bug.

**Comment by arenekosreal** [comment]
Unfortunately exporting game with godot 4.3 still not work. I have even tried calling `dotnet build -c ExportRelease` before exporting. But I could not launch editor and then try exporting because each command is invoked in a headless environment. So I guess it may because that godot editor did some trick to fix this problem. I am going to try to export game with godot editor to see if there is any change.

Just for reference, here are log files when building with makepkg:
[thrive-0.7.0-3-x86_64-prepare.log](https://github.com/user-attachments/files/16847760/thrive-0.7.0-3-x86_64-prepare.log)
[thrive-0.7.0-3-x86_64-build.log](https://github.com/user-attachments/files/16847764/thrive-0.7.0-3-x86_64-build.log)
[thrive-0.7.0-3-x86_64-check.log](https://github.com/user-attachments/files/16847765/thrive-0.7.0-3-x86_64-check.log)
[thrive-0.7.0-3-x86_64-package.log](https://github.com/user-attachments/files/16847766/thrive-0.7.0-3-x86_64-package.log)

**Comment by hhyyrylainen** [comment]
Still it is weird that our CI setup manages to make working builds, though maybe it is different because it uses the dehydrated build system I wrote where it takes the .pck file and removes usually not changing files out. The builds are then put back together on the client computer where the separately tracked files are put back into the .pck file. But this process shouldn't result in any different .pck file than before. So I'm not sure if that could explain the difference.

A just completed fresh build log is here: https://dev.revolutionarygamesstudio.com/ci/1/build/11390/jobs/1 inspecting it, it looks like it is totally missing the `Cannot connect to` log lines. That export log has all kinds of errors but that's the one that the CI build doesn't have but your log does have. So maybe that is really the real reason? It's also missing any errors about `ERROR: Failed to create an autoload, script 'res://src/engine/Invoke.cs' is not compiling.` 

Could that have something to do with the runtime environment or something not supporting running the C# code? Or maybe the default Godot editor settings doesn't use dotnet for general building meaning the source build fails only for internal editor usage? I see quite a few potential causes of the symptom of the editor being unable to see that the button signal connections are valid.

**Comment by arenekosreal** [comment]
Good news, I tried exporting latest commit `27ae9a8dfb10d4d7831d98963330187dedfff77c` after imported in godot editor, then this problem disappeared, even build with `--headless` flag. Then I will try to export same commit directly after cloned repository without imported into godot editor to check if my guess is correct.

**Comment by arenekosreal** [comment]
Yes, this is the problem. If I export the game directly without imported into editor, those buttons are not working. Let me see if I can find out any solution for this.

**Comment by hhyyrylainen** [comment]
There should be command line Godot flags to run the editor until it has imported all assets and then exit (though I remember there being github issues about that getting stuck and needing a fallback max iterations count variable to exit properly, though that bug may be fixed in Godot 4.3).

**Comment by arenekosreal** [comment]
OK, finally I managed to export a working game by running
```bash
godot-mono --headless --build-solutions --quit
godot-mono --headless --import
```
before do actual exporting.

I will close this issue now because I managed to solve this problem, but I think you may consider adding a note at [setup_instructions](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/setup_instructions.md) to help people who have to face same situation.

**Comment by hhyyrylainen** [comment]
I'll keep that in mind if we add like official instructions for building Thrive inside a podman container. For now the supported way to build Thrive is with our custom build script, which is already explained in the setup instructions file.
