### ISSUE TITLE
Rework cell movement

### ISSUE THREAD

**Issue by TjWhale** [Revolutionary-Games/Thrive#557]
Movement is too slow in 0.3.4 and turning is painfully slow.

Soln: Movement to be rebalanced in line with the prototype made by @andross  and myself, with all cells turning at a constant speed. 

Prototype is [here.](https://github.com/Revolutionary-Games/thrive-prototypes/blob/master/movement_balancing/movement_prototype_const_rot.py) The key lines are 416-508.

The goal is that movement should feel fluid and smooth. Cells without flagella should be able to move, but only slowly.

**Comment by Untrustedlife** [comment]
Should we just merge trevisolian's code?

**Comment by hhyyrylainen** [comment]
It still needs changes. See my review on the pull request for why I'm not ready to merge it yet.

**Comment by TjWhale** [comment]
I think the main problem with movement is that it's too slow. I'd like to try both systems, moving with mouse and moving with a + d, at the same time if possible, to see which is better after the speed and turning rate have been nicely balanced. I'm open to a + d being better but I'm not sure it will feel right and I don't want to commit to it now.

**Comment by TjWhale** [comment]
If it's possible I think it would be helpful to have all the movement related constants defined in a single place, that would make balancing quite straightforward. Things like "force per flagella" "mass of cells" "friction" "turning rate" etc could all be at the top of a non-compiled file somewhere and then it would be easy to change them to get the game feeling good. Is this possible?

**Comment by hhyyrylainen** [comment]
I think it should be pretty easy to change the values to be / be multiplied by a constant in config.as It will be more difficult to have the force be a non-linear curve if it needs to be controlled that way to make it feel better, though. 


-------- Alkuperäinen viesti --------Lähettäjä: TjWhale <notifications@github.com> Päivämäärä: 5.6.2018  14.21  (GMT+02:00) Saaja: Revolutionary-Games/Thrive <Thrive@noreply.github.com> Kopio: Henri Hyyryläinen <henri.hyyrylainen@gmail.com>, Comment <comment@noreply.github.com> Aihe: Re: [Revolutionary-Games/Thrive] Rework cell movement (#557) 
If it's possible I think it would be helpful to have all the movement related constants defined in a single place, that would make balancing quite straightforward. Things like "force per flagella" "mass of cells" "friction" "turning rate" etc could all be at the top of a non-compiled file somewhere and then it would be easy to change them to get the game feeling good. Is this possible?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/Revolutionary-Games/Thrive/issues/557#issuecomment-394673183","url":"https://github.com/Revolutionary-Games/Thrive/issues/557#issuecomment-394673183","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Revolutionary-Games/Thrive","title":"Revolutionary-Games/Thrive","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Revolutionary-Games/Thrive"}},"updates":{"snippets":[{"icon":"PERSON","message":"@TjWhale in #557: If it's possible I think it would be helpful to have all the movement related constants defined in a single place, that would make balancing quite straightforward. Things like \"force per flagella\" \"mass of cells\" \"friction\" \"turning rate\" etc could all be at the top of a non-compiled file somewhere and then it would be easy to change them to get the game feeling good. Is this possible?"}],"action":{"name":"View Issue","url":"https://github.com/Revolutionary-Games/Thrive/issues/557#issuecomment-394673183"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Re: [Revolutionary-Games/Thrive] Rework cell movement (#557)",
"sections": [
{
"text": "",
"activityTitle": "**TjWhale**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@TjWhale",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Revolutionary-Games/Thrive\",\n\"issueId\": 557,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Revolutionary-Games/Thrive\",\n\"issueId\": 557\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Revolutionary-Games/Thrive/issues/557#issuecomment-394673183"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 323291388\n}"
}
],
"themeColor": "26292E"
}

**Comment by Untrustedlife** [comment]
You said something about not wanting a constant turn rate on teh dev forum, should we remove that from this issue?

**Comment by TjWhale** [comment]
In this issue when I say "constant rate" I mean that it doesn't matter how large a cell is (as in how many organelles it has) it should always turn at the same rate. However the turning should be proportional to the distance left to turn. (For larger turns you turn faster)

The other option was to have larger cells turn more slowly however I am worried they will be painfully slow so I'd like to try them out being able to turn just like small cells. We can iterate on it later.

Apologies if this was confusing.

**Comment by hhyyrylainen** [comment]
This is still blocked by https://github.com/Revolutionary-Games/Thrive/issues/618 
Once that is done this needs just some tweaking to the constants:
```
const auto FLAGELLA_BASE_FORCE = 4.0f;
const auto CELL_BASE_THRUST = 1.0f;
//! The drag force is calculated by taking the current velocity and multiplying it by this.
//! This must be negative!
const auto CELL_DRAG_MULTIPLIER = -0.4f;
//! If drag is below this it isn't applied to let the cells come to a halt properly
const auto CELL_REQUIRED_DRAG_BEFORE_APPLY = 0.001;
```

**Comment by Untrustedlife** [comment]
Im pretty confident this can be closed

**Comment by TjWhale** [comment]
Does the drag work properly at the moment or does it still do that left drifting?

**Comment by Untrustedlife** [comment]
I fixed the drifting, the only "issue" and i dont think it is one, is that you stop more slowly now.

**Comment by Untrustedlife** [comment]
I think its properly fixed in this issue: Its properly fixed in this commit: https://github.com/Revolutionary-Games/Thrive/commit/2b985cf62d9f094fa6b065d2c5596e629468e86c

Maybe needs some minor tweaking to the constants now but now it makes sure there is no drift. ANd you stop faster.

**Comment by Untrustedlife** [comment]
Once we confirm what everyone likes in terms of movement  and change those constants this should be good to close @TjWhale , what do you think?
