### ISSUE TITLE
Some UI regressions (Comparing to Godot 3 version)

### ISSUE THREAD

**Issue by TheESN** [Revolutionary-Games/Thrive#5634]
"At Cursor" font lost its bold property
![изображение](https://github.com/user-attachments/assets/4c2278ef-2acd-40b0-8f93-110711bf9e91)

Godot 3 Version
![изображение](https://github.com/user-attachments/assets/e52885ec-bfe6-41d8-bcd2-b2c956492aff)

Population box text and number aren't properly centered. HP and ATP numbers are way smaller and don't fill the majority of the box
![изображение](https://github.com/user-attachments/assets/0d6fa9b4-a449-44db-99c1-0f7843dae2b0)

Godot 3 Version
![изображение](https://github.com/user-attachments/assets/1fbc5482-b009-4094-ab4f-f7b45a3138dc)

**Comment by TheESN** [comment]
Also I noticed that padding here become much smaller
![изображение](https://github.com/user-attachments/assets/062034c2-fe53-492a-a7b6-4424cf58ed61)

Godot 3 Version
![изображение](https://github.com/user-attachments/assets/aeda6ac7-5432-4b5b-b49f-6971d96acbad)

This reduced padding cause inconsistency with Editor UI that kept original one
![изображение](https://github.com/user-attachments/assets/7ec5ee81-efc2-4f19-ab46-58ee344aed81)

**Comment by hhyyrylainen** [comment]
Bold looks different in Godot 4 so the bold fonts aren't based on the super bold font anymore. Fixing that would be very annoying and require tweaking a multitude of font settings files. 

Font heights (i.e. the height the text boxes want to take up) is vastly different in Godot 4, so it is not possible to make the heights the same as before (I already spent over an hour fighting this when porting the game to Godot 4).

What I was able to do in a few minutes was to re-align the bottom left panels so that they are 9 pixels above the bottom left buttons in microbe and multicellular stage (as the distance in the microbe editor was 9 pixels before the buttons start touching the bottom of the panel). Also I'll center align the population numbers. I can't really do the other stuff in reasonable amount of time and it's been months since the update and no one else has said anything so let's just call the other changes "improvements" or tweaks.
