### ISSUE TITLE
Moving cell in body plan editor is invisible if no cell type is selected

### ISSUE THREAD

**Issue by betovalero** [Revolutionary-Games/Thrive#5636]
### Describe the bug

Wen i was in early multicelular mode and used the move action on a Cell, the Cell turnd invizible antil i placed It (excuse the bad english)

### To Reproduce

Get to the multicelular stage, and move a Cell clicking on It 
with right Button on the mouse and selecting "move", It Will turn invisível until you place It (It Will remove also all rotation)

### Expected behaviour

Have the Cell be veseble Wile you place It 

### System information

Windows and bad( dont have that much informativo)
V0.7.1

### Game Logs

Got to multicelular mode, has an adicional Cell type for movment, moved cuz i cul aford an extra Cell but neded a new shape to stay bilateraly cimetric, and found this glich ( and i continue to encounter It cuz i kept mesing up the shape)

### Additional Context

I am Brazilian

**Comment by hhyyrylainen** [comment]
I think I found out what the issue is despite the description being hard to read:
- Create a body plan with a few cells
- Exit the editor
- Enter the editor again
- Do not select any cell type
- Right click a cell and select move
- The cell to be placed is invisible *until* a cell type is selected

So the bug is the same as there was in the cell editor some time ago where a moved thing is invisible if nothing is selected. Should be a simple enough fix in the code to force visible the moved cell even if there is no action selected.

**Comment by betovalero** [comment]
No, that is not How the glich hapend, i right click an existing Cell, selected the option "move", and It was invisible antil i placed It (and Lost all rotation)

**Comment by betovalero** [comment]
Actuly i miss intérpretes, you até right, How to delet a coment in Github?

**Comment by hhyyrylainen** [comment]
The three dots at the top right of the message has the options what to do with it.

![kuva](https://github.com/user-attachments/assets/149a6f38-e19d-4020-9b56-e23fccab35e2)
