### ISSUE TITLE
Patch dropdown selector in editor doesn't always contain all patches

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#5668]
I started a freebuild game, played a few generations, saved and loaded in the editor, and then played a bit more. Then I noticed an event in a patch that seemingly didn't exist. I was able to select it from the map but it is totally missing from the selector for some reason:

![kuva](https://github.com/user-attachments/assets/0c94142c-781f-4e1a-bb93-1ada1f129c6d)

![2024-11-08_16 05 35 2873](https://github.com/user-attachments/assets/98a244f5-7788-4621-a193-59bb49a9e056)

This might be freebuild specific, but in case it isn't I'm putting it into high priority issues.

**Comment by dligr** [comment]
It seems like this issue is a matter of the editor's report component using `Patch.GetClosestConnectedPatches()`, which by default has a limit of returning 20 patches

Without it, though, there is the problem that the dropdown doesn't have a scrollbar:
![image](https://github.com/user-attachments/assets/90ec2ecb-ad78-4e3d-8e7b-d0fd8035dc75)

**Comment by hhyyrylainen** [comment]
Godot usually puts a scrollbar if the dropdown doesn't entirely fit on screen. Is there anything missing in the screenshot or? Godot 3 was more finicky when it showed the scrollbar where dropdowns that barely didn't fit didn't get a scrollbar incorrectly.

**Comment by dligr** [comment]
I had to modify the patch map editor to get a high enough patch count, but the scroll bar does appear:
![image](https://github.com/user-attachments/assets/e928fcd7-4125-4aa8-ae85-f502a28ec234)
