### ISSUE TITLE
Compounds turning Black after logging back into game

### ISSUE THREAD

**Issue by Squidyman56** [Revolutionary-Games/Thrive#594]
I am sorry if this post is re-complaining about a previous issue already talked about.

So I have noticed that after the game closes or crashes, and I load a previous save file, that all compounds are from then on completely black. I had tries exiting and going back to the save file, and they are still black. Closing the game and going back in doesn't work. The only thing that I find works is making a new game. With the new game the compounds all have color, but they only stay that way until the game closes or crashes.

I hope that this is being worked on for the 0.4.0 release (or what ever release is coming next). 

Have you guys experienced this too? I am using Ubuntu 17.10 with the Kde environment.

**Comment by hhyyrylainen** [comment]
I remember seeing a few people saying the same thing on our community forums.
I have not had this happen to me but I think that this is caused by the old save system that directly saved entity state and restored it, thus permanently making the cloud entities black if the colour bugged out once, at least until you start a new game.
If you haven't noticed / heard we have switched engines and right now there is no saving system, but my plan for one is to make it work differently than what the last release had. Though, progress have been slow with only me and one other programmer contributing to getting all features working again during the summer, and both of us had full time programming jobs. So it might be still a while until the next release.

**Comment by hhyyrylainen** [comment]
Added review and impeded flags as this just needs to be confirmed to not happen once the new save system is done.

**Comment by Untrustedlife** [comment]
definetly not happening anymore

**Comment by hhyyrylainen** [comment]
We don't have saving yet... so...
