### ISSUE TITLE
Two falls

### ISSUE THREAD

**Issue by Vojta3310** [Revolutionary-Games/Thrive#617]
Hello i find two bugs:
1) After exit game to the main menu, press new game cause this error:
  ```
Lua error detected! ../scripts/microbe_stage/camera.lua:29: attempt to index local 'playerNode' (a nil value):
    ../scripts/microbe_stage/camera.lua:29 (method update)
    ../scripts/lua_engine/game_state.lua:186 (method update)
    ../scripts/lua_engine/lua_engine.lua:145 (method update)
    ../scripts/game.lua:39
```

2) Segmentation fault after few minutes of playing, i cant find source of this error. With valgrind i get this:
```
FPS: 57.5968 avg frame duration: 13.12749 ms
--6760-- REDIR: 0x4ef3b50 (libc.so.6:__stpcpy_sse2_unaligned) redirected to 0x4c36200 (__stpcpy_sse2_unaligned)
Segmentation fault (core dumped)
```

i run game on Linux Mint 19
Thank for solution.

**Comment by hhyyrylainen** [comment]
Since the last release we have changed engines and done major rework on most parts of the game. The latest work is going on here: https://github.com/Revolutionary-Games/Thrive/tree/fix_everything
and as such this issue has either been already solved or testing needs to be done on the latest code to find issues.

**Comment by Vojta3310** [comment]
Thank you.
