### ISSUE TITLE
Engulfing seems slightly broken after physics engine change

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#627]
I noticed while trying to egulf that most of the time the physics between engulfing cells doesn't get disabled. Not really sure why that is the case, probably something to do with the physics callbacks with bullet.

**Comment by Untrustedlife** [comment]
There was a similar issue with the toxin callback, which i just fixed. Ill look into this now.

**Comment by hhyyrylainen** [comment]
I think this is fine. After playing the old physics engine version a bit I think the engulfing works just the same.

**Comment by Untrustedlife** [comment]
Im not so sure this is the same anymore after watching kinesis play.

**Comment by hhyyrylainen** [comment]
@Untrustedlife will you take a look at this soon?

**Comment by Untrustedlife** [comment]
Yeah. Yesterday was process day so now that that is fixed I will look at other stuff.

**Comment by Untrustedlife** [comment]
Okay, its fixed in this commit. The only caveat is that you have to hit the cell you are engulfing AFTER you turn on engulf mode, if you hit them and turn on engulf mod while touching them you will not engulf them, what you have to do then is back up and slam back into them. And it only has that issue rarely.
The issues were that the variables weren't actually initialized (and after initilizing and checking them they finally returned the correct values) and callbacks work differently in bullet, among other things. But its fixed now.
Im going to close this now, but if @hhyyrylainen  doenst think my fix is sufficient we can just reopen this.
https://github.com/Revolutionary-Games/Thrive/commit/9ef920367f4495a15ff203037e0ebb66def0aac5
