### ISSUE TITLE
Rework death

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#676]
Discussed here in detail: https://forum.revolutionarygamesstudio.com/t/reworking-death/547
Summary: cells shouldn't instantly explode into a compound cloud instead they should spawn particles that slowly release stuff.
This will share a lot of code with: https://github.com/Revolutionary-Games/Thrive/issues/675

This may make the death model fixing obsolete: https://github.com/Revolutionary-Games/Thrive/issues/601

**Comment by Untrustedlife** [comment]
I suppose this will be my next problem. For this, the big hard bit is making them break into chunks and dealing with that somehow, then we use the new system from #675 to make those chunks excrete compounds. And add a component that makes things "rot away" when out of compounds in a compound bag (or wrap that into the the venter system, though that would be weird because we don't want every thing that runs out of compounds to disappear)

**Comment by Untrustedlife** [comment]
​we should add a method of attaching to iron chunks and chunks of dead microbes for the full fungul/scavenger experience, so maybe its about time we add a pilus type. Whichever kind is used to attach to things in a hostile manner. Alongside this.

**Comment by Untrustedlife** [comment]
(well maybe anyway)

**Comment by Untrustedlife** [comment]
I have created the branch for this

**Comment by hhyyrylainen** [comment]
And then proceeded to do all kinds of other changes on it...
We need one branch specifically named for random changes to keep all the feature branches from getting clogged up.

**Comment by Untrustedlife** [comment]
I think the bug fixes I did are fine. I specifically needed the toxin bug fix as this branch is very related to combat as it’s about reworking death.

**Comment by Untrustedlife** [comment]
But maybe a RandomChanges branch or a bugfixes branch would be useful
