### ISSUE TITLE
ER and Golgi stay after removing Nucleus

### ISSUE THREAD

**Issue by Uniow** [Revolutionary-Games/Thrive#825]
Nucleus organelles are not deleted when the nucleus is when pressing +new button.

**To Reproduce**
1. Go to the editor
2. Place the nucleus
3. Confirm changes
4. Go to the editor again
5. Press +New

**Expected behavior**
![image](https://user-images.githubusercontent.com/52930856/65378436-62220280-dcb8-11e9-8e68-16c631489bcd.png)

**Comment by hhyyrylainen** [comment]
There's probably an issue in the nucleus organelle removal code where it doesn't delete the two child entities for some reason.

**Comment by Dak2896** [comment]
The weird thing is that ER and GOLGI are not removed only from player cell.
And from editor the same functions are invoked.

Could be the problem that ER and GOLGI are child of microbeEntity instead of nucleus entity, so when we add them they attach to microbe when we remove nucleus, it is removed from template, so new cells are created without but player cell keep it become entity is not regenerated?

**Comment by hhyyrylainen** [comment]
It's a concious design decision that the player entity is never destroyed. The organelle removal function needs to handle nucleus correctly.

**Comment by Dak2896** [comment]
I just create a new entity called nucles when nucleus is added, and add as parent this new entity instead of microbe.

When nucleus removed i just destroy this entity and seems work.

**Comment by hhyyrylainen** [comment]
The problem is likely that this method should have entity queue destroy calls:
https://github.com/Revolutionary-Games/Thrive/blob/master/scripts/microbe_stage/organelle_components/nucleus_organelle.as#L70

**Comment by hhyyrylainen** [comment]
https://github.com/Revolutionary-Games/Thrive/pull/828
