### ISSUE TITLE
AI cells should decide to move immediately

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#889]
Currently the AI waits about 3 seconds after a cell spawns before it does anything. It would be better to have the cells immediately think and start moving. This is only really visible when respawning.

**Comment by Dak2896** [comment]
Should we remove completely the value AI_TIME_INTERVAL and is check in microbe ai, or just set it to 0 because could be useful one day for test something when  cells "stay" for a while?

**Comment by hhyyrylainen** [comment]
AI_TIME_INTERVAL is used so that the AI doesn't completely lag the game by running all the time.
The default value / which way it is incremented and checked, should be changed so that newly spawned cells get to do an AI think (almost) immediately.

**Comment by Dak2896** [comment]
So the best value value would be 0 but it cost too much computation do it every frame, do you think could be good solution tweak that value when we respawn after editor to 0 and for the rest of time having it at 150 as now? 

I'm also thinking if could be good calculate it in different way depending on which generation we are because at beginning there are not so many AI cells stuff to calculate a very  good precision will not affect so much the game experience but in high late  generation more precision would be needed without creating too much lag does it make sense for you?

**Comment by hhyyrylainen** [comment]
I think that this only really needs change to the initial value for the time passed in the MicrobeAIComponent so that it starts off doing an AI update on that cell.

**Comment by TheRexYo** [comment]
Okay, so I'm working on this issue. What I've decided to try and do is add a variable in the cell's AI (to determine whether or not it's initialized yet) and have the Run() function execute a nearly identical FullRun() function that checks if a cell's AI is using the variable and, if so, executing the same code as in Run() (albeit in a separate function). This may be a waste of line-space, but it gets the job done, I think. Just to be sure we're on the right page, the problem is that, when a cell spawns, it doesn't immediately use its AI, correct?

**Comment by TheRexYo** [comment]
Well, I just noticed that the code already contains the function:
	MicrobeAIControllerComponent(){

		intervalRemaining = reevalutationInterval;
	}
Isn't that exactly what you're looking for? Is this issue fixed already?

**Comment by TheRexYo** [comment]
Here's a demonstration of the AI instantly reacting: 

![2019-12-16-19-08-16](https://user-images.githubusercontent.com/58960341/70955962-289f3000-2038-11ea-93f4-e9459ad3980a.gif)

Sorry about the quality - I used an online converter to go from Mp4 to GIF for the picture.

**Comment by hhyyrylainen** [comment]
For me when I hit the suicide button and respawn in an area where there are a lot of cells, the cells often stay stationary for a couple of seconds. That's the thing I want to solve.

**Comment by TheRexYo** [comment]
Okay, I think I fixed it this time. I noticed the issue myself finally, and decided to try and fix it. When I re-added the code that I used for my first attempt at fixing the issue, it worked like a charm! Is there a way I can send you the code, or...?

**Comment by TheRexYo** [comment]
If you need proof, you might want to try it yourself, because I haven't had time to demonstrate it in a video since I fixed it.

**Comment by hhyyrylainen** [comment]
You should open a pull request with your changes: https://github.com/Revolutionary-Games/Thrive/pulls
There are many tutorials around for how to do github pull request. One that I've been linking everywhere is this description on how to make a fork and pull request: https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by hhyyrylainen** [comment]
When I brought back the old AI code this started again. So despite running an update immediately the AI seems to decide to just chill very often.
