### ISSUE TITLE
Auto-Evo for player

### ISSUE THREAD

**Issue by TheRexYo** [Revolutionary-Games/Thrive#915]
I don't know if this is intended, but Auto-Evo doesn't work for the player. The player's individual successes should have an impact, but their choices in species creation should too, because not all members of the player's species are accounted for in the current system - just the player him/herself.

If needed, the minimum population to thrive could be increased to expand play-time. Auto-Evo is REALLY beneficial to a species population (just load up Free-Build and look at those numbers!) and should thus be given to the player to avoid an in-balance between them and the AI.

To be honest, this may not be the best place to post this thought, but either way, thanks for reading!

**Comment by hhyyrylainen** [comment]
Yeah, github issues are not the place to request new features. However this is a feature that has long been planned, so I'm going to keep this open, but if someone attempts to do this, then there's a ton of work here.

Here's some summary of what's been decided regarding auto-evo on the player species:
- auto-evo as well as the player's individual success should affect the player population (maybe something like 80-20 split for individual success and auto-evo)
- the player species should probably not spread automatically
- the editor needs a lot more statistics and a preview for upcoming numbers while editing so that the player doesn't feel like they get randomly hit with population changes. This is the part that takes a lot of work
- This is also a big one, issue https://github.com/Revolutionary-Games/Thrive/issues/766 needs to be solved first as currently the auto-evo things are random

**Comment by TheRexYo** [comment]
For #766, I believe it would be best to wait for Nick's Auto Evo to be completed so that it can be implemented as the means of calculating population. As an added bonus, this would also remove the need to design a new equation from scratch.
