### ISSUE TITLE
Engulfing your own species should be blocked

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive#919]
Due to engulfing only checking size difference, you can sometimes engulf your own species. It should be made so that you can't engulf your own species.

**Comment by GatoCreador887** [comment]
From Discord some time ago:

> Me:
> Currently you can engulf members of your own species without penalty. This should probably be changed in one of these two ways:
> - A check is added to prevent engulfment of your own species.
> - A penalty is added to discourage engulfment of your own species. I like this one because it presents some interesting strategy, because population would go down while allowing the player to enter the editor sooner.

> DonGororo:
> Oh yeah, i wonder what effects would cannibalism have on the auto evo algorithm

> TJWhale:
> Yeah good point gato, a tradeoff where you lose pop in exchange for compounds now sounds interesting

> TJWhale:
We were talking about having your species learn from how you do things. So for example your whole species would become more cannibalistic if you were a cannibal, that would be quite a cool way of making the trade.

**Comment by 1n48yg** [comment]
How realistic or viable is cannibalism on a cellular level? The neural networks of such organisms in response to other organisms is probably going to be flee, murder or ignore. If a specimen puts organisms from its own species into the category that it kills, would it be able to develop any exceptions to such a rule? Such as what happens when two cells are created from the same meiosis process, do they instantly commit mutual cannibalism or have a "cooldown" before they see each other as food?

Another concern of mine is wouldn't cannibalistic cells be effectively locked in the cellular stage as they cannot bond?

**Comment by hhyyrylainen** [comment]
Those are some interesting problems, which I want to avoid by just banning cannibalism for now.

**Comment by hhyyrylainen** [comment]
This should already be fixed in 0.4.3

**Comment by hhyyrylainen** [comment]
Reopening because of: https://community.revolutionarygamesstudio.com/t/strategies-for-0-4-3/2403/5?u=hhyyrylainen
